// Generated by vm-gen -- standalone protected JavaScript VM.
// Do not edit: the embedded image is integrity-checked at startup.
'use strict';
(function () {
var IMAGE_B64 = "VkcCABMCAMK/+AbWBUVANF1rthyZGwf+sEAgEK26OzsRAKsAAAB8M/vzn60kOQJyHowRVj62BQUdy4wHaTjUo2aVZXUfpcfrxiAupq+VfigWjNxEizQZiaUoS66ai0d274cxuG5Y6MpbcBGoRIFeFbqdcvT3RXtHFOjqZXU29edlqfVIN9ppFGt6/QofeNRczJflhQvTsMrp6ONE83PCedY15wHDBPLVHMnNenD8xqJR9zqhGwQbmpd14ynRBhXlkrBx3Qo4Wt9RinLwMm5IpKYIAAxfVng2endKOGw2WHkAAAAAAf8AaAAAAPp9N06G+mZSO3hXK/FlUr7LvA0dlStwDPSxzwtjsRweFsS0mB3+1MhApE13VdYz+FYuQmtNyaicPh0CKOZfamhUXaQpqnvrmegs49L5APp5NTe955OmK3z34D/iAbBquti9ONIoc76oCF9CSGt0WXo2AQIAAAH/ABIAAADgaCo3pnZSkYjAa5U74/9CUdsIX3AzY2JLQnMBAwAAAf8AOAAAAO5CHiPF8cD+1DESjBVdGGXbIia7nl9gBueOPi7g+IvupDSHoWaQQA4KP4VpxMcujmPdoLQAJCHuCF9kRFV4bUJZAQMAAAH/ADgAAADVOhHU4230LSFjtYMO3jGR5LFa/gUlDQQ1dHHA0vDCVjfvcUJ1M2WDDVWWUTdJ6oJyNO3fWisf4w92YWxpZGF0ZUxpY2Vuc2UDAwAAAf8ACAAAABjlCqIdno7EDWZsdXNoRGlzcGF0Y2gBBQAAA/8AGgAAAPtkoeBAB9eoTPDxz3ZH7pcIqgcgOfB/S843CmF1ZGl0VGFibGUABQAAAv8AHAAAAHTnyIB0AYCUggXy2QSShtX5Nhcv7c3J8KwwOC0KYXVkaXRUYWJsZQEFAAAD/wAXAAAAT0KeX89yxp3iVsNtl2gJ/R6v7XlD/gs=";
var __REQUIRE_BASE__ = "C:\\Users\\eadan\\OneDrive\\Desktop\\Claude-Projects\\vm-gen\\tests";
var SALT = 1371042758;
var OP = {
HALT: 0,
PUSH_CONST: 1,
PUSH_TRUE: 2,
PUSH_FALSE: 3,
PUSH_NULL: 4,
POP: 5,
DUP: 6,
LOAD: 7,
STORE: 8,
ADD: 9,
SUB: 10,
MUL: 11,
DIV: 12,
MOD: 13,
NEG: 14,
NOT: 15,
EQ: 16,
NEQ: 17,
LT: 18,
GT: 19,
LTE: 20,
GTE: 21,
BAND: 22,
BOR: 23,
BXOR: 24,
SHL: 25,
SHR: 26,
JMP: 27,
JZ: 28,
JNZ: 29,
CALL: 30,
RET: 31,
CALL_HOST: 32,
NEW_ARR: 33,
ARR_GET: 34,
ARR_SET: 35,
PRINT: 36,
NEW_OBJ: 37,
CLOSURE: 38,
LOAD_UP: 39,
STORE_UP: 40,
LOAD_UPVALUE: 41,
STORE_UPVALUE: 42,
CLOSE_UPVALUE: 43,
CALL_VALUE: 44,
LOAD_THIS: 45,
LOAD_ARGS: 46,
YIELD: 47,
CALL_METHOD: 48,
NEW: 49,
NEW_VALUE: 50,
TRY: 51,
END_TRY: 52,
THROW: 53,
LOADADD: 54,
LOADSUB: 55,
LOADLT: 56,
CONSTADD: 57,
AWAIT: 58
};
var FORMAT_MAJOR = 2;
var EXPECTED_OPCOUNT = 59;
var MAX_STEPS = 200000000;
var MAX_DEPTH = 512;
var MAX_OBJECTS = 5000000;
var MAX_STRING = 33554432;
var objCount = 0;
function guardStr(s) { if (MAX_STRING && typeof s === 'string' && s.length > MAX_STRING) throw new Error('resource limit: string size exceeded'); return s; }
function guardObj() { if (MAX_OBJECTS && ++objCount > MAX_OBJECTS) throw new Error('resource limit: object budget exceeded'); }
var MASK32 = 0x100000000;
function mul32(a, b) {
a = a % MASK32; b = b % MASK32;
var ah = Math.floor(a / 65536), al = a % 65536;
var r = ((ah * b) % 65536) * 65536 + al * b;
return r % MASK32;
}
function lcgNext(s) { return (mul32(s, 1664525) + 1013904223) % MASK32; }
function ksByte(s) { return Math.floor(s / 16777216) % 256; }
function fnSeed(codeSeed, idx) { return (codeSeed + mul32(idx, 2654435761)) % MASK32; }
function roundSeed(cs, idx, r) { return r === 0 ? fnSeed(cs, idx) : (fnSeed(cs, idx) + mul32(r, 2246822519)) % MASK32; }
function cipher(bytes, seed) {
var st = seed % MASK32, out = new Array(bytes.length);
for (var i = 0; i < bytes.length; i++) { st = lcgNext(st); out[i] = (bytes[i] ^ ksByte(st)) & 0xff; }
return out;
}
function decRounds(bytes, cs, idx, rounds) { var out = bytes; for (var r = 0; r < rounds; r++) out = cipher(out, roundSeed(cs, idx, r)); return out; }
function fnv1a(bytes) {
var h = 2166136261;
for (var i = 0; i < bytes.length; i++) {
var low = h % 256;
h = h - low + (low ^ bytes[i]);
h = mul32(h, 16777619);
}
return h % MASK32;
}
function keyedMac(keyBytes, bytes) {
var m1 = fnv1a(keyBytes.concat(bytes));
var m2 = fnv1a(bytes.concat(keyBytes).concat([0x9e, 0x37, 0x79, 0xb9]));
return [m1 & 0xff, (m1 >>> 8) & 0xff, (m1 >>> 16) & 0xff, (m1 >>> 24) & 0xff,
m2 & 0xff, (m2 >>> 8) & 0xff, (m2 >>> 16) & 0xff, (m2 >>> 24) & 0xff];
}
function strBytes(s) {
if (!s) return [];
if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'utf8'));
var e = unescape(encodeURIComponent(s)), o = [];
for (var i = 0; i < e.length; i++) o.push(e.charCodeAt(i));
return o;
}
function envKey() {
if (typeof process !== 'undefined' && process.env && process.env.VMGEN_KEY) return process.env.VMGEN_KEY;
if (typeof globalThis !== 'undefined' && globalThis.VMGEN_KEY) return globalThis.VMGEN_KEY;
return '';
}
function decodeB64(s) {
if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'base64'));
var bin = atob(s), a = new Array(bin.length);
for (var i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
return a;
}
function utf8(bytes) {
if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('utf8');
return decodeURIComponent(escape(String.fromCharCode.apply(null, bytes)));
}
function load() {
var b = decodeB64(IMAGE_B64);
if (b[0] !== 0x56 || b[1] !== 0x47) throw new Error('bad magic');
var major = b[2]; // b[3]=minor b[4]=flags b[5]=profile b[6]=arch
if (major !== FORMAT_MAJOR) throw new Error('unsupported image format major ' + major);
var checksum = b[7] + b[8] * 256 + b[9] * 65536 + b[10] * 16777216;
var meta = [b[2], b[3], b[4], b[5], b[6]];
var domainBytes = b.slice(11, 27); // 4x u32: header, dispatch, const, fn
function d32(o) { return domainBytes[o] + domainBytes[o + 1] * 256 + domainBytes[o + 2] * 65536 + domainBytes[o + 3] * 16777216; }
var dHeader = d32(0), dDispatch = d32(4), dConst = d32(8), dFn = d32(12);
var SIGNED = (b[4] & 4) !== 0;
var sigBytes = SIGNED ? b.slice(27, 35) : [];
var body = b.slice(SIGNED ? 35 : 27);
if (fnv1a(meta.concat(domainBytes).concat(sigBytes).concat(body)) !== (checksum % MASK32)) throw new Error('integrity check failed: image tampered');
if (fnv1a(meta) !== dHeader) throw new Error('integrity check failed: header domain');
if (SIGNED) {
var mac = keyedMac(strBytes(envKey()), body);
var sigOk = true;
for (var si = 0; si < 8; si++) { if (mac[si] !== sigBytes[si]) sigOk = false; }
if (!sigOk) throw new Error('authenticity/authorization check failed');
}
var p = 0;
function u8() { return body[p++]; }
function u16() { var v = body[p] | (body[p + 1] << 8); p += 2; return v; }
function u32() { var v = body[p] + body[p + 1] * 256 + body[p + 2] * 65536 + body[p + 3] * 16777216; p += 4; return v; }
var obfMaster = u32();
var masterSeed = (obfMaster ^ SALT) >>> 0;
var numCanon = u8();
if (numCanon !== EXPECTED_OPCOUNT) throw new Error('integrity check failed: VM/opcode-table mismatch');
var rs = masterSeed || 0x9e3779b9;
function rng() { rs = lcgNext(rs); return rs; }
var pool = []; for (var pi = 0; pi < 256; pi++) pool.push(pi);
for (var pj = 255; pj > 0; pj--) { var jj = rng() % (pj + 1); var tt = pool[pj]; pool[pj] = pool[jj]; pool[jj] = tt; }
var identPerm = (b[4] & 8) !== 0;
var byte2canon = {};
var permBytes = [];
for (var i = 0; i < numCanon; i++) { var pb = identPerm ? i : pool[i]; byte2canon[pb] = i; permBytes.push(pb); }
var codeSeed = rng() % MASK32;
var constSeed = rng() % MASK32;
if (fnv1a(permBytes) !== dDispatch) throw new Error('integrity check failed: dispatch domain');
var constCount = u16();
var encConstLen = u32();
var encConst = body.slice(p, p + encConstLen); p += encConstLen;
if (fnv1a(encConst) !== dConst) throw new Error('integrity check failed: constant domain');
var constBlob = cipher(encConst, constSeed);
var consts = [];
var cp = 0;
for (var c = 0; c < constCount; c++) {
var tag = constBlob[cp++];
if (tag === 2) {
var A = constBlob[cp] + constBlob[cp + 1] * 256 + constBlob[cp + 2] * 65536 + constBlob[cp + 3] * 16777216; cp += 4;
var B = constBlob[cp] + constBlob[cp + 1] * 256 + constBlob[cp + 2] * 65536 + constBlob[cp + 3] * 16777216; cp += 4;
consts.push((A ^ B) >>> 0);
} else {
var len = constBlob[cp] | (constBlob[cp + 1] << 8); cp += 2;
var raw = constBlob.slice(cp, cp + len); cp += len;
var str = utf8(raw);
consts.push(tag === 0 ? parseFloat(str) : str);
}
}
var fnCount = u16();
var fns = [];
var fnAll = [];
for (var f = 0; f < fnCount; f++) {
var nl = u8();
var name = utf8(body.slice(p, p + nl)); p += nl;
var nparams = u8();
var nlocals = u16();
var nUp = u8();
var upvals = [];
for (var uu = 0; uu < nUp; uu++) { var fl = u8(); var ui = u16(); upvals.push({ fromLocal: fl === 1, index: ui }); }
var protLevel = u8();
var restParam = u8(); // 0xff = none
var fnFlags = u8();   // bit0 = generator
var codeLen = u32();
var enc = body.slice(p, p + codeLen); p += codeLen;
fnAll = fnAll.concat(enc);
fns.push({ name: name, nparams: nparams, nlocals: nlocals, upvals: upvals, restParam: (restParam === 0xff ? null : restParam), generator: (fnFlags & 1) !== 0, async: (fnFlags & 2) !== 0, code: decRounds(enc, codeSeed, f, protLevel) });
}
if (fnv1a(fnAll) !== dFn) throw new Error('integrity check failed: function domain');
return { byte2canon: byte2canon, consts: consts, fns: fns };
}
var __vmset = (typeof WeakSet !== 'undefined') ? new WeakSet() : null;
var __vmeta = (typeof WeakMap !== 'undefined') ? new WeakMap() : null;
function mkObj(proto) { var o = proto ? Object.create(proto) : {}; if (__vmset) __vmset.add(o); return o; }
function isObj(v) { return v !== null && typeof v === 'object' && !Array.isArray(v) && v.__closure !== true && __vmset && __vmset.has(v); }
function metaOf(o) { if (!__vmeta) return null; var m = __vmeta.get(o); if (!m) { m = {}; __vmeta.set(o, m); } return m; }
function isClosure(v) { return !!v && typeof v === 'object' && v.__closure === true; }
function mkCells(n) { var a = new Array(n); for (var i = 0; i < n; i++) a[i] = { v: null }; return a; }
function objKeys(o) { var r = []; for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) r.push(k); return r; }
function mkFrame(fn, args, upvals, thisObj) {
var locals = mkCells(fn.nlocals), np = fn.nparams;
for (var k = 0; k < np; k++) locals[k].v = (k < args.length ? args[k] : null);
if (fn.restParam != null && fn.restParam >= 0) locals[fn.restParam].v = args.slice(fn.restParam);
return { fn: fn, ip: 0, locals: locals, upvals: upvals || [], thisObj: thisObj, args: args };
}
function toStr(v) {
if (v === null || v === undefined) return 'null';
if (v === true) return 'true';
if (v === false) return 'false';
if (typeof v === 'number') return String(v);
if (typeof v === 'string') return v;
if (isClosure(v)) return '<fn>';
if (Array.isArray(v)) { var a = []; for (var j = 0; j < v.length; j++) a.push(toStr(v[j])); return '[' + a.join(', ') + ']'; }
if (isObj(v)) { var r = [], ks = objKeys(v); for (var i = 0; i < ks.length; i++) r.push(ks[i] + ': ' + toStr(v[ks[i]])); return '{' + r.join(', ') + '}'; }
return String(v);
}
function truthy(v) { return !(v === null || v === undefined || v === false || v === 0 || v === ''); }
function u32of(n) { return n >>> 0; }
function idxGet(obj, key) {
if (isClosure(obj)) {
if (key === 'bind') return function () { var t = arguments[0], b = Array.prototype.slice.call(arguments, 1); return function () { return __runMethod(obj, t, b.concat(Array.prototype.slice.call(arguments))); }; };
if (key === 'call') return function () { return __runMethod(obj, arguments[0], Array.prototype.slice.call(arguments, 1)); };
if (key === 'apply') return function () { return __runMethod(obj, arguments[0], arguments[1] || []); };
return undefined;
}
if (typeof obj === 'string') { if (key === 'length') return obj.length; return obj[key]; }
if (obj === null || obj === undefined) throw new Error('cannot index ' + toStr(obj));
var r = obj[key]; // native property access: VM objects, arrays, class instances, host objects, getters
if (r === undefined && isObj(obj) && !(key in obj)) return null; // VM objects read missing keys as null
return r;
}
function idxSet(obj, key, val) {
if (obj && (typeof obj === 'object' || typeof obj === 'function')) { obj[key] = val; return; }
throw new Error('cannot assign index of ' + toStr(obj));
}
function syncSettled(state, value) {
var t = { __syncthen: true, state: state, value: value };
t.then = function (onF, onR) {
try {
if (t.state === 'fulfilled') return syncSettled('fulfilled', onF ? onF(t.value) : t.value);
if (onR) return syncSettled('fulfilled', onR(t.value));
return t;
} catch (e) { return syncSettled('rejected', e); }
};
t.catch = function (onR) { return t.then(undefined, onR); };
t.finally = function (fn) { if (fn) fn(); return t; };
return t;
}
function toSyncPromise(v) {
if (v && v.__syncthen) return v;
if (v && typeof v.then === 'function') { var got, err, ok = true; v.then(function (x) { got = x; }, function (e) { ok = false; err = e; }); return ok ? syncSettled('fulfilled', got) : syncSettled('rejected', err); }
return syncSettled('fulfilled', v);
}
var __SyncPromise = {
resolve: function (v) { return toSyncPromise(v); },
reject: function (e) { return syncSettled('rejected', e); },
all: function (arr) { var out = []; for (var i = 0; i < arr.length; i++) { var s = toSyncPromise(arr[i]); if (s.state === 'rejected') return s; out.push(s.value); } return syncSettled('fulfilled', out); },
race: function (arr) { return arr.length ? toSyncPromise(arr[0]) : syncSettled('fulfilled', undefined); },
};
var __globals = Object.create(null);
var __hostg = {
undefined: undefined, NaN: NaN, Infinity: Infinity, globalThis: (typeof globalThis !== 'undefined' ? globalThis : undefined), console: console,
Object: Object, Array: Array, Math: Math, JSON: JSON, Number: Number, String: String, Boolean: Boolean,
Promise: Promise, Map: Map, Set: Set, WeakMap: (typeof WeakMap !== 'undefined' ? WeakMap : undefined), WeakSet: (typeof WeakSet !== 'undefined' ? WeakSet : undefined),
Symbol: (typeof Symbol !== 'undefined' ? Symbol : undefined), Proxy: (typeof Proxy !== 'undefined' ? Proxy : undefined), Reflect: (typeof Reflect !== 'undefined' ? Reflect : undefined),
RegExp: RegExp, Date: Date, Error: Error, TypeError: TypeError, RangeError: RangeError,
parseInt: parseInt, parseFloat: parseFloat, isNaN: isNaN, isFinite: isFinite,
process: (typeof process !== 'undefined' ? process : undefined), Buffer: (typeof Buffer !== 'undefined' ? Buffer : undefined),
setTimeout: (typeof setTimeout !== 'undefined' ? setTimeout : undefined)
};
function __requireBridge(spec) {
try {
var path = require('path');
var base = (typeof __REQUIRE_BASE__ === 'string' && __REQUIRE_BASE__) ? __REQUIRE_BASE__ : process.cwd();
if (spec && (/^\.\.?([\\/]|$)/.test(spec) || spec.indexOf('/') === 0 || /^[A-Za-z]:[\\/]/.test(spec))) return require(path.resolve(base, spec));
return require(spec);
} catch (e) { try { return require(spec); } catch (e2) { return undefined; } }
}
function __typeof(v) {
if (v === undefined) return 'undefined';
if (v === null) return 'object';
if (isClosure(v) || typeof v === 'function') return 'function';
if (Array.isArray(v) || isObj(v)) return 'object';
return typeof v;
}
function __instanceof(o, c) {
if (typeof c === 'function') { try { return o instanceof c; } catch (e) { return false; } }
if (isObj(c) && c['__isClass']) { var k = isObj(o) ? metaOf(o).classRef : null; while (k && isObj(k)) { if (k === c) return true; k = k['__super']; } return false; }
return false;
}
var __runMethod = null; // set inside run(): (closure, thisObj, args) -> result
var __runGeneratorFn = null; // set inside run(): (closure, thisObj) -> yielded array
function __newObj(args) {
var cls = args[0], rest = args.slice(1);
if (typeof cls === 'function') {
if (typeof Proxy !== 'undefined' && cls === Proxy && rest.length === 2 && isObj(rest[1])) {
var h = rest[1], nh = {}, hk = objKeys(h);
for (var hi = 0; hi < hk.length; hi++) { var hv = h[hk[hi]]; nh[hk[hi]] = isClosure(hv) ? toNativeJs(hv) : hv; }
rest[1] = nh;
}
try { for (var a = 0; a < rest.length; a++) rest[a] = toNativeJs(rest[a]); return new (Function.prototype.bind.apply(cls, [null].concat(rest)))(); } catch (e) { return null; }
}
if (isObj(cls) && cls['__isClass']) {
var chain = [], c = cls;
while (c && isObj(c) && c['__isClass']) { chain.unshift(c); c = c['__super']; }
var proto = {};
for (var i = 0; i < chain.length; i++) { var m = chain[i]['__methods']; if (isObj(m)) { var mk = objKeys(m); for (var j = 0; j < mk.length; j++) proto[mk[j]] = m[mk[j]]; } }
var inst = mkObj(proto);
metaOf(inst).classRef = cls;
var ctor = null;
for (var ci = chain.length - 1; ci >= 0; ci--) { if (chain[ci]['__ctor']) { ctor = chain[ci]['__ctor']; break; } }
if (ctor && isClosure(ctor) && __runMethod) __runMethod(ctor, inst, rest);
return inst;
}
return null;
}
function host(name, args) {
switch (name) {
case 'len': return Array.isArray(args[0]) ? args[0].length : (isObj(args[0]) ? objKeys(args[0]).length : String(args[0]).length);
case 'str': return toStr(args[0]);
case 'num': return parseFloat(args[0]);
case 'floor': return Math.floor(args[0]);
case 'abs': return Math.abs(args[0]);
case 'rand': return Math.random();
case 'time': return Date.now();
case 'push': args[0].push(args[1]); return args[0];
case '__extend': {
var a = args[0], it = args[1];
var symIt = (it && typeof Symbol !== 'undefined') ? it[Symbol.iterator] : undefined;
if (Array.isArray(it) || typeof it === 'string') { for (var ei = 0; ei < it.length; ei++) a.push(it[ei]); }
else if (isClosure(symIt) && __runGeneratorFn) { var seq = __runGeneratorFn(symIt, it); for (var gi = 0; gi < seq.length; gi++) a.push(seq[gi]); } // VM generator [Symbol.iterator]()
else if (typeof symIt === 'function') { var iter = symIt.call(it), st; while (!(st = iter.next()).done) a.push(st.value); }
else if (isObj(it)) { var ks = objKeys(it); for (var ki = 0; ki < ks.length; ki++) a.push(it[ks[ki]]); }
return a;
}
case 'keys': return (args[0] && typeof args[0] === 'object') ? objKeys(args[0]) : [];
case 'has': return (args[0] && typeof args[0] === 'object') ? (('' + args[1]) in args[0]) : false;
case '__setglobal': __globals[args[0]] = args[1]; return args[1];
case '__getglobal': {
var nm = args[0];
if (Object.prototype.hasOwnProperty.call(__globals, nm)) return __globals[nm];
if (nm === 'require') return __requireBridge;
if (nm === 'Promise') return __SyncPromise; // synchronous promise model
if (Object.prototype.hasOwnProperty.call(__hostg, nm)) return __hostg[nm];
return undefined;
}
case 'typeof': return __typeof(args[0]);
case 'bitnot': return ~(Number(args[0]) || 0);
case 'pow': return Math.pow(args[0], args[1]);
case 'instanceof': return __instanceof(args[0], args[1]);
case 'inop': { var k = args[0], o = args[1]; if (Array.isArray(o)) return Number(k) >= 0 && Number(k) < o.length; if (o && typeof o === 'object') return (('' + k) in o); return false; }
case 'require': return __requireBridge(args[0]);
case '__new': return __newObj(args);
case '__defaccessor': {
var o = args[0], name = args[1], kind = args[2], fn = args[3];
if (o && typeof o === 'object') {
var d = Object.getOwnPropertyDescriptor(o, name);
var desc = { enumerable: true, configurable: true };
if (d && d.get) desc.get = d.get; if (d && d.set) desc.set = d.set;
if (kind === 'get') desc.get = (function (f) { return function () { return __runMethod(f, this, []); }; })(fn);
else desc.set = (function (f) { return function (v) { __runMethod(f, this, [v]); }; })(fn);
try { Object.defineProperty(o, name, desc); } catch (e) {}
}
return o;
}
case '__regex': { try { return new RegExp(args[0], args[1] || ''); } catch (e) { return null; } }
default: throw new Error('unknown host builtin ' + name);
}
}
function run(prog) {
var b2c = prog.byte2canon, consts = prog.consts, fns = prog.fns;
var stack = [];
var frames = [];
var handlers = []; // { frame, framesLen, stackLen, addr }
var frame = { fn: fns[0], ip: 0, locals: mkCells(fns[0].nlocals), upvals: [] };
function rd8() { return frame.fn.code[frame.ip++]; }
function rd16() { var lo = frame.fn.code[frame.ip], hi = frame.fn.code[frame.ip + 1]; frame.ip += 2; return lo | (hi << 8); }
function raise(value) {
while (handlers.length) {
var h = handlers.pop();
frames.length = h.framesLen;
frame = h.frame;
stack.length = h.stackLen;
frame.ip = h.addr;
stack.push(value);
return true;
}
return false;
}
var steps = 0;
function exec(retDepth) {
for (;;) {
if (MAX_STEPS && ++steps > MAX_STEPS) throw new Error('resource limit: instruction budget exceeded');
var op = b2c[rd8()];
try {
switch (op) {
case OP.HALT: return undefined;
case OP.PUSH_CONST: stack.push(consts[rd16()]); break;
case OP.PUSH_TRUE: stack.push(true); break;
case OP.PUSH_FALSE: stack.push(false); break;
case OP.PUSH_NULL: stack.push(null); break;
case OP.POP: stack.pop(); break;
case OP.DUP: stack.push(stack[stack.length - 1]); break;
case OP.LOAD: stack.push(frame.locals[rd16()].v); break;
case OP.STORE: frame.locals[rd16()].v = stack.pop(); break;
case OP.LOAD_UP: stack.push(frame.upvals[rd16()].v); break;
case OP.STORE_UP: frame.upvals[rd16()].v = stack.pop(); break;
case OP.ADD: { var b = stack.pop(), a = stack.pop(); stack.push((typeof a === 'number' && typeof b === 'number') ? a + b : guardStr(toStr(a) + toStr(b))); break; }
case OP.SUB: { var b = stack.pop(), a = stack.pop(); stack.push(a - b); break; }
case OP.MUL: { var b = stack.pop(), a = stack.pop(); stack.push(a * b); break; }
case OP.DIV: { var b = stack.pop(), a = stack.pop(); stack.push(a / b); break; }
case OP.MOD: { var b = stack.pop(), a = stack.pop(); stack.push(a % b); break; }
case OP.NEG: stack.push(-stack.pop()); break;
case OP.NOT: stack.push(!truthy(stack.pop())); break;
case OP.EQ: { var b = stack.pop(), a = stack.pop(); stack.push(a === b); break; }
case OP.NEQ: { var b = stack.pop(), a = stack.pop(); stack.push(a !== b); break; }
case OP.LT: { var b = stack.pop(), a = stack.pop(); stack.push(a < b); break; }
case OP.GT: { var b = stack.pop(), a = stack.pop(); stack.push(a > b); break; }
case OP.LTE: { var b = stack.pop(), a = stack.pop(); stack.push(a <= b); break; }
case OP.GTE: { var b = stack.pop(), a = stack.pop(); stack.push(a >= b); break; }
case OP.BAND: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a & b)); break; }
case OP.BOR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a | b)); break; }
case OP.BXOR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a ^ b)); break; }
case OP.SHL: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a << b)); break; }
case OP.SHR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a >>> b)); break; }
case OP.JMP: { frame.ip = rd16(); break; }
case OP.JZ: { var addr = rd16(); if (!truthy(stack.pop())) frame.ip = addr; break; }
case OP.JNZ: { var addr = rd16(); if (truthy(stack.pop())) frame.ip = addr; break; }
case OP.CALL: {
var fnIdx = rd16(), argc = rd8();
if (MAX_DEPTH && frames.length + 1 > MAX_DEPTH) throw new Error('resource limit: call depth exceeded');
var callee = fns[fnIdx];
var cargs = new Array(argc);
for (var k = argc - 1; k >= 0; k--) cargs[k] = stack.pop();
if (callee.generator) { stack.push(runGenerator(callee, cargs, [], undefined)); break; }
if (callee.async) { stack.push(toSyncPromise(runClosure({ __closure: true, fn: fnIdx, upvals: [] }, cargs, undefined))); break; }
frames.push(frame);
frame = mkFrame(callee, cargs, [], undefined);
break;
}
case OP.CALL_VALUE: {
var vargc = rd8();
if (MAX_DEPTH && frames.length + 1 > MAX_DEPTH) throw new Error('resource limit: call depth exceeded');
var vargs = new Array(vargc);
for (var vk = vargc - 1; vk >= 0; vk--) vargs[vk] = stack.pop();
var vcallee = stack.pop();
if (typeof vcallee === 'function' && !isClosure(vcallee)) { for (var vn=0;vn<vargs.length;vn++) vargs[vn]=toNativeJs(vargs[vn]); stack.push(vcallee.apply(null, vargs)); break; }
if (!isClosure(vcallee)) throw new Error('value is not callable: ' + toStr(vcallee));
var vfn = fns[vcallee.fn];
if (vfn.generator) { stack.push(runGenerator(vfn, vargs, vcallee.upvals, undefined)); break; }
if (vfn.async) { stack.push(toSyncPromise(runClosure(vcallee, vargs, undefined))); break; }
frames.push(frame);
frame = mkFrame(vfn, vargs, vcallee.upvals, undefined);
break;
}
case OP.LOAD_THIS: { stack.push(frame.thisObj !== undefined ? frame.thisObj : null); break; }
case OP.LOAD_ARGS: { stack.push(frame.args || []); break; }
case OP.YIELD: { var yv = stack.pop(); if (frame.yields) frame.yields.push(yv); stack.push(null); break; }
case OP.CALL_METHOD: {
var margc = rd8();
var margs = new Array(margc);
for (var mk = margc - 1; mk >= 0; mk--) margs[mk] = stack.pop();
var mcallee = stack.pop();
var mrecv = stack.pop();
if (typeof mcallee === 'function' && !isClosure(mcallee)) { for (var mn=0;mn<margs.length;mn++) margs[mn]=toNativeJs(margs[mn]); stack.push(mcallee.apply(mrecv, margs)); break; }
if (!isClosure(mcallee)) throw new Error('value is not callable: ' + toStr(mcallee));
var mfn = fns[mcallee.fn];
if (mfn.generator) { stack.push(runGenerator(mfn, margs, mcallee.upvals, mrecv)); break; }
if (mfn.async) { stack.push(toSyncPromise(runClosure(mcallee, margs, mrecv))); break; }
frames.push(frame);
frame = mkFrame(mfn, margs, mcallee.upvals, mrecv);
break;
}
case OP.AWAIT: {
var av = stack.pop();
if (av && av.__syncthen) { if (av.state === 'rejected') throw { __vmthrow: true, v: av.value }; stack.push(av.value); }
else if (av && (typeof av === 'object' || typeof av === 'function') && typeof av.then === 'function') { var sp = toSyncPromise(av); if (sp.state === 'rejected') throw { __vmthrow: true, v: sp.value }; stack.push(sp.value); }
else stack.push(av);
break;
}
case OP.CLOSE_UPVALUE: { rd16(); break; } // locals are already heap cells
case OP.LOADADD: { var laI = rd16(); var laX = stack.pop(), laB = frame.locals[laI].v; stack.push((typeof laX === 'number' && typeof laB === 'number') ? laX + laB : toStr(laX) + toStr(laB)); break; }
case OP.LOADSUB: { var lsI = rd16(); stack.push(stack.pop() - frame.locals[lsI].v); break; }
case OP.LOADLT: { var llI = rd16(); stack.push(stack.pop() < frame.locals[llI].v); break; }
case OP.CONSTADD: { var caI = rd16(); var caX = stack.pop(), caB = consts[caI]; stack.push((typeof caX === 'number' && typeof caB === 'number') ? caX + caB : toStr(caX) + toStr(caB)); break; }
case OP.CLOSURE: {
var cidx = rd16();
var cfn = fns[cidx];
var ups = new Array(cfn.upvals.length);
for (var cu = 0; cu < cfn.upvals.length; cu++) { var d = cfn.upvals[cu]; ups[cu] = d.fromLocal ? frame.locals[d.index] : frame.upvals[d.index]; }
stack.push({ __closure: true, fn: cidx, upvals: ups });
break;
}
case OP.RET: {
var rv = stack.pop();
if (frames.length === retDepth) return rv; // returned to caller (main or runClosure)
frame = frames.pop();
stack.push(rv);
break;
}
case OP.CALL_HOST: {
var nameIdx = rd16(), hargc = rd8();
var hargs = new Array(hargc);
for (var j = hargc - 1; j >= 0; j--) hargs[j] = stack.pop();
stack.push(host(consts[nameIdx], hargs));
break;
}
case OP.NEW_ARR: {
guardObj();
var n = rd16(), arr = new Array(n);
for (var m = n - 1; m >= 0; m--) arr[m] = stack.pop();
stack.push(arr);
break;
}
case OP.NEW_OBJ: {
guardObj();
var on = rd16(), pairs = [];
for (var om = 0; om < on; om++) { var ov = stack.pop(), ok = stack.pop(); pairs.push([ok, ov]); }
pairs.reverse();
var obj = mkObj();
for (var pi = 0; pi < pairs.length; pi++) { var pk = pairs[pi][0]; obj[typeof pk === 'symbol' ? pk : ('' + pk)] = pairs[pi][1]; }
stack.push(obj);
break;
}
case OP.ARR_GET: { var idx = stack.pop(), arr2 = stack.pop(); stack.push(idxGet(arr2, idx)); break; }
case OP.ARR_SET: { var val = stack.pop(), idx2 = stack.pop(), arr3 = stack.pop(); idxSet(arr3, idx2, val); stack.push(val); break; }
case OP.TRY: { handlers.push({ frame: frame, framesLen: frames.length, stackLen: stack.length, addr: rd16() }); break; }
case OP.END_TRY: { handlers.pop(); break; }
case OP.THROW: { var tv = stack.pop(); if (!raise(tv)) throw new Error('uncaught exception: ' + toStr(tv)); break; }
case OP.PRINT: { var out = (typeof process !== 'undefined' && process.stdout) ? function (s) { process.stdout.write(s + '\n'); } : console.log; out(toStr(stack.pop())); break; }
default: throw new Error('illegal opcode ' + op + ' at ip=' + (frame.ip - 1));
}
} catch (e) {
if (e instanceof Error && /illegal opcode|resource limit/.test(e.message)) throw e;
var ev = (e && e.__vmthrow) ? e.v : e;
if (!raise(ev)) throw (e && e.__vmthrow) ? new Error('uncaught exception: ' + toStr(ev)) : e;
}
}
}
function runClosure(closure, args, thisObj) {
var fn = fns[closure.fn];
frames.push(frame);
var rd = frames.length;
frame = mkFrame(fn, args, closure.upvals, thisObj);
var rv = exec(rd);
frame = frames.pop();
return rv;
}
__runMethod = function (closure, thisObj, args) { return runClosure(closure, args, thisObj); };
function runGenerator(fn, args, upvals, thisObj) {
frames.push(frame);
var rd = frames.length;
frame = mkFrame(fn, args, upvals, thisObj);
var yields = frame.yields = []; // a real array (spreads / iterates natively)
exec(rd);
frame = frames.pop();
return yields;
}
__runGeneratorFn = function (closure, thisObj) { return runGenerator(fns[closure.fn], [], closure.upvals, thisObj); };
toNativeJs = function (v) {
if (v && v.__closure) return function () { var a = []; for (var i = 0; i < arguments.length; i++) a.push(arguments[i]); return runClosure(v, a); };
return v;
};
return exec(0);
}
var toNativeJs = function (v) { return v; };
try {
run(load());
} catch (e) {
if (typeof console !== 'undefined') console.error('[vm-gen] ' + e.message);
if (typeof process !== 'undefined' && process.exit) process.exit(1);
}
})();
