// Generated by vm-gen -- standalone protected JavaScript VM.
// Do not edit: the embedded image is integrity-checked at startup.
'use strict';
(function () {
  var IMAGE_B64 = "VkcCAAMBAP9FNjgdwK0IuZSjvUuKduQCTG/8xIpMOFMXwCQ5oFpyCorq3nwCeAYPVLYSxRYNYG40CTZmRUYYvuPKHGK0ASSJYVLssFxKOt85na5OwkhMeTwVgJJCBAAYAAAA6yUatlwnPrsiNiuIaxeU5opgfanL8YtsAwAFJG1haW4AAAAAARgAAAA46yEao76oTLshNoezBRa0CvwFoNyJGisEdGVzdAAAAAABDAAAAHDQFeVqRVScBrFWMgUkYW5vbgAAAAABCAAAAHW7CIx0wVOM";

  var OP = {
  HALT: 0,
  PUSH_CONST: 1,
  PUSH_TRUE: 2,
  PUSH_FALSE: 3,
  PUSH_NULL: 4,
  POP: 5,
  DUP: 6,
  LOAD: 7,
  STORE: 8,
  ADD: 9,
  SUB: 10,
  MUL: 11,
  DIV: 12,
  MOD: 13,
  NEG: 14,
  NOT: 15,
  EQ: 16,
  NEQ: 17,
  LT: 18,
  GT: 19,
  LTE: 20,
  GTE: 21,
  BAND: 22,
  BOR: 23,
  BXOR: 24,
  SHL: 25,
  SHR: 26,
  JMP: 27,
  JZ: 28,
  JNZ: 29,
  CALL: 30,
  RET: 31,
  CALL_HOST: 32,
  NEW_ARR: 33,
  ARR_GET: 34,
  ARR_SET: 35,
  PRINT: 36,
  NEW_OBJ: 37,
  CLOSURE: 38,
  LOAD_UP: 39,
  STORE_UP: 40,
  LOAD_UPVALUE: 41,
  STORE_UPVALUE: 42,
  CLOSE_UPVALUE: 43,
  CALL_VALUE: 44,
  LOAD_THIS: 45,
  CALL_METHOD: 46,
  NEW: 47,
  NEW_VALUE: 48,
  TRY: 49,
  END_TRY: 50,
  THROW: 51,
  LOADADD: 52,
  LOADSUB: 53,
  LOADLT: 54,
  CONSTADD: 55,
  AWAIT: 56
  };

  var FORMAT_MAJOR = 2;
  var EXPECTED_OPCOUNT = 57;
  var MAX_STEPS = 0;
  var MAX_DEPTH = 1024;

  var MASK32 = 0x100000000;
  function mul32(a, b) {
    a = a % MASK32; b = b % MASK32;
    var ah = Math.floor(a / 65536), al = a % 65536;
    var r = ((ah * b) % 65536) * 65536 + al * b;
    return r % MASK32;
  }
  function lcgNext(s) { return (mul32(s, 1664525) + 1013904223) % MASK32; }
  function ksByte(s) { return Math.floor(s / 16777216) % 256; }
  function fnSeed(codeSeed, idx) { return (codeSeed + mul32(idx, 2654435761)) % MASK32; }
  function roundSeed(cs, idx, r) { return r === 0 ? fnSeed(cs, idx) : (fnSeed(cs, idx) + mul32(r, 2246822519)) % MASK32; }
  function cipher(bytes, seed) {
    var st = seed % MASK32, out = new Array(bytes.length);
    for (var i = 0; i < bytes.length; i++) { st = lcgNext(st); out[i] = (bytes[i] ^ ksByte(st)) & 0xff; }
    return out;
  }
  function decRounds(bytes, cs, idx, rounds) { var out = bytes; for (var r = 0; r < rounds; r++) out = cipher(out, roundSeed(cs, idx, r)); return out; }
  function fnv1a(bytes) {
    var h = 2166136261;
    for (var i = 0; i < bytes.length; i++) {
      var low = h % 256;
      h = h - low + (low ^ bytes[i]);
      h = mul32(h, 16777619);
    }
    return h % MASK32;
  }
  function keyedMac(keyBytes, bytes) {
    var m1 = fnv1a(keyBytes.concat(bytes));
    var m2 = fnv1a(bytes.concat(keyBytes).concat([0x9e, 0x37, 0x79, 0xb9]));
    return [m1 & 0xff, (m1 >>> 8) & 0xff, (m1 >>> 16) & 0xff, (m1 >>> 24) & 0xff,
            m2 & 0xff, (m2 >>> 8) & 0xff, (m2 >>> 16) & 0xff, (m2 >>> 24) & 0xff];
  }
  function strBytes(s) {
    if (!s) return [];
    if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'utf8'));
    var e = unescape(encodeURIComponent(s)), o = [];
    for (var i = 0; i < e.length; i++) o.push(e.charCodeAt(i));
    return o;
  }
  function envKey() {
    if (typeof process !== 'undefined' && process.env && process.env.VMGEN_KEY) return process.env.VMGEN_KEY;
    if (typeof globalThis !== 'undefined' && globalThis.VMGEN_KEY) return globalThis.VMGEN_KEY;
    return '';
  }

  function decodeB64(s) {
    if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'base64'));
    var bin = atob(s), a = new Array(bin.length);
    for (var i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
    return a;
  }
  function utf8(bytes) {
    if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('utf8');
    return decodeURIComponent(escape(String.fromCharCode.apply(null, bytes)));
  }

  // ---- parse + verify the protected image ----
  function load() {
    var b = decodeB64(IMAGE_B64);
    if (b[0] !== 0x56 || b[1] !== 0x47) throw new Error('bad magic');
    var major = b[2]; // b[3]=minor b[4]=flags b[5]=profile b[6]=arch
    if (major !== FORMAT_MAJOR) throw new Error('unsupported image format major ' + major);
    var checksum = b[7] + b[8] * 256 + b[9] * 65536 + b[10] * 16777216;
    var meta = [b[2], b[3], b[4], b[5], b[6]];
    var domainBytes = b.slice(11, 27); // 4x u32: header, dispatch, const, fn
    function d32(o) { return domainBytes[o] + domainBytes[o + 1] * 256 + domainBytes[o + 2] * 65536 + domainBytes[o + 3] * 16777216; }
    var dHeader = d32(0), dDispatch = d32(4), dConst = d32(8), dFn = d32(12);
    var SIGNED = (b[4] & 4) !== 0;
    var sigBytes = SIGNED ? b.slice(27, 35) : [];
    var body = b.slice(SIGNED ? 35 : 27);
    // master integrity: header meta + domain table + optional signature + body.
    if (fnv1a(meta.concat(domainBytes).concat(sigBytes).concat(body)) !== (checksum % MASK32)) throw new Error('integrity check failed: image tampered');
    // independent domain: header.
    if (fnv1a(meta) !== dHeader) throw new Error('integrity check failed: header domain');
    // authenticity / entitlement: verify the keyed signature against a runtime key.
    if (SIGNED) {
      var mac = keyedMac(strBytes(envKey()), body);
      var sigOk = true;
      for (var si = 0; si < 8; si++) { if (mac[si] !== sigBytes[si]) sigOk = false; }
      if (!sigOk) throw new Error('authenticity/authorization check failed');
    }

    var p = 0;
    function u8() { return body[p++]; }
    function u16() { var v = body[p] | (body[p + 1] << 8); p += 2; return v; }
    function u32() { var v = body[p] + body[p + 1] * 256 + body[p + 2] * 65536 + body[p + 3] * 16777216; p += 4; return v; }

    var codeSeed = u32(), constSeed = u32();
    var numCanon = u8();
    // runtime integrity: the image's opcode table must match this VM build.
    if (numCanon !== EXPECTED_OPCOUNT) throw new Error('integrity check failed: VM/opcode-table mismatch');
    var byte2canon = {};
    var permBytes = [];
    for (var i = 0; i < numCanon; i++) { var pb = u8(); byte2canon[pb] = i; permBytes.push(pb); }
    // independent domain: dispatch (opcode permutation).
    if (fnv1a(permBytes) !== dDispatch) throw new Error('integrity check failed: dispatch domain');

    var constCount = u16();
    var encConstLen = u32();
    var encConst = body.slice(p, p + encConstLen); p += encConstLen;
    // independent domain: constants.
    if (fnv1a(encConst) !== dConst) throw new Error('integrity check failed: constant domain');
    var constBlob = cipher(encConst, constSeed);
    var consts = [];
    var cp = 0;
    for (var c = 0; c < constCount; c++) {
      var tag = constBlob[cp++];
      if (tag === 2) {
        // concealed integer: recover A xor B
        var A = constBlob[cp] + constBlob[cp + 1] * 256 + constBlob[cp + 2] * 65536 + constBlob[cp + 3] * 16777216; cp += 4;
        var B = constBlob[cp] + constBlob[cp + 1] * 256 + constBlob[cp + 2] * 65536 + constBlob[cp + 3] * 16777216; cp += 4;
        consts.push((A ^ B) >>> 0);
      } else {
        var len = constBlob[cp] | (constBlob[cp + 1] << 8); cp += 2;
        var raw = constBlob.slice(cp, cp + len); cp += len;
        var str = utf8(raw);
        consts.push(tag === 0 ? parseFloat(str) : str);
      }
    }

    var fnCount = u16();
    var fns = [];
    var fnAll = [];
    for (var f = 0; f < fnCount; f++) {
      var nl = u8();
      var name = utf8(body.slice(p, p + nl)); p += nl;
      var nparams = u8();
      var nlocals = u16();
      var nUp = u8();
      var upvals = [];
      for (var uu = 0; uu < nUp; uu++) { var fl = u8(); var ui = u16(); upvals.push({ fromLocal: fl === 1, index: ui }); }
      var protLevel = u8();
      var codeLen = u32();
      var enc = body.slice(p, p + codeLen); p += codeLen;
      fnAll = fnAll.concat(enc);
      fns.push({ name: name, nparams: nparams, nlocals: nlocals, upvals: upvals, code: decRounds(enc, codeSeed, f, protLevel) });
    }
    // independent domain: functions.
    if (fnv1a(fnAll) !== dFn) throw new Error('integrity check failed: function domain');
    return { byte2canon: byte2canon, consts: consts, fns: fns };
  }

  // ---- value model: number | string | boolean | null | Array | VMObj | closure | cell ----
  function VMObj() { this.keys = []; this.map = {}; }
  VMObj.prototype.get = function (k) { k = '' + k; return Object.prototype.hasOwnProperty.call(this.map, k) ? this.map[k] : null; };
  VMObj.prototype.set = function (k, v) { k = '' + k; if (!Object.prototype.hasOwnProperty.call(this.map, k)) this.keys.push(k); this.map[k] = v; };
  VMObj.prototype.has = function (k) { return Object.prototype.hasOwnProperty.call(this.map, '' + k); };
  function isObj(v) { return v instanceof VMObj; }
  function isClosure(v) { return !!v && typeof v === 'object' && v.__closure === true; }
  function mkCells(n) { var a = new Array(n); for (var i = 0; i < n; i++) a[i] = { v: null }; return a; }

  function toStr(v) {
    if (v === null || v === undefined) return 'null';
    if (v === true) return 'true';
    if (v === false) return 'false';
    if (typeof v === 'number') return String(v);
    if (typeof v === 'string') return v;
    if (isObj(v)) { var r = []; for (var i = 0; i < v.keys.length; i++) { var k = v.keys[i]; r.push(k + ': ' + toStr(v.map[k])); } return '{' + r.join(', ') + '}'; }
    if (isClosure(v)) return '<fn>';
    if (Array.isArray(v)) { var a = []; for (var j = 0; j < v.length; j++) a.push(toStr(v[j])); return '[' + a.join(', ') + ']'; }
    return String(v);
  }
  function truthy(v) { return !(v === null || v === undefined || v === false || v === 0 || v === ''); }
  function u32of(n) { return n >>> 0; }
  function idxGet(obj, key) {
    if (isObj(obj)) return obj.get(key);
    if (Array.isArray(obj)) return obj[key];
    if (typeof obj === 'string') { if (key === 'length') return obj.length; return obj[key]; }
    if (obj === null || obj === undefined) throw new Error('cannot index ' + toStr(obj));
    return obj[key]; // native object / function / number
  }
  function idxSet(obj, key, val) {
    if (isObj(obj)) { obj.set(key, val); return; }
    if (Array.isArray(obj)) { obj[key] = val; return; }
    if (obj && (typeof obj === 'object' || typeof obj === 'function')) { obj[key] = val; return; }
    throw new Error('cannot assign index of ' + toStr(obj));
  }

  // Shared global environment + host globals (real JS built-ins by name).
  var __globals = Object.create(null);
  var __hostg = {
    undefined: undefined, NaN: NaN, Infinity: Infinity, globalThis: (typeof globalThis !== 'undefined' ? globalThis : undefined), console: console,
    Object: Object, Array: Array, Math: Math, JSON: JSON, Number: Number, String: String, Boolean: Boolean,
    Promise: Promise, Map: Map, Set: Set, WeakMap: (typeof WeakMap !== 'undefined' ? WeakMap : undefined), WeakSet: (typeof WeakSet !== 'undefined' ? WeakSet : undefined),
    Symbol: (typeof Symbol !== 'undefined' ? Symbol : undefined), Proxy: (typeof Proxy !== 'undefined' ? Proxy : undefined), Reflect: (typeof Reflect !== 'undefined' ? Reflect : undefined),
    RegExp: RegExp, Date: Date, Error: Error, TypeError: TypeError, RangeError: RangeError,
    parseInt: parseInt, parseFloat: parseFloat, isNaN: isNaN, isFinite: isFinite,
    process: (typeof process !== 'undefined' ? process : undefined), Buffer: (typeof Buffer !== 'undefined' ? Buffer : undefined),
    setTimeout: (typeof setTimeout !== 'undefined' ? setTimeout : undefined)
  };
  function __requireBridge(spec) {
    try {
      var path = require('path');
      var base = (typeof __REQUIRE_BASE__ === 'string' && __REQUIRE_BASE__) ? __REQUIRE_BASE__ : process.cwd();
      if (spec && (spec.indexOf('./') === 0 || spec.indexOf('../') === 0 || spec.indexOf('/') === 0 || /^[A-Za-z]:[\\/]/.test(spec))) return require(path.resolve(base, spec));
      return require(spec);
    } catch (e) { try { return require(spec); } catch (e2) { return undefined; } }
  }
  function __typeof(v) {
    if (v === undefined) return 'undefined';
    if (v === null) return 'object';
    if (isClosure(v) || typeof v === 'function') return 'function';
    if (Array.isArray(v) || isObj(v)) return 'object';
    return typeof v;
  }
  function __instanceof(o, c) {
    if (typeof c === 'function') { try { return o instanceof c; } catch (e) { return false; } }
    if (isObj(c) && c.get('__isClass')) { var k = isObj(o) ? o.__classRef : null; while (k && isObj(k)) { if (k === c) return true; k = k.get('__super'); } return false; }
    return false;
  }
  function __newObj(args) {
    var cls = args[0], rest = args.slice(1);
    if (typeof cls === 'function') { try { return new (Function.prototype.bind.apply(cls, [null].concat(rest)))(); } catch (e) { return null; } }
    if (isObj(cls) && cls.get('__isClass')) {
      var inst = new VMObj(); inst.__classRef = cls;
      var chain = [], c = cls;
      while (c && isObj(c) && c.get('__isClass')) { chain.unshift(c); c = c.get('__super'); }
      for (var i = 0; i < chain.length; i++) { var m = chain[i].get('__methods'); if (isObj(m)) for (var j = 0; j < m.keys.length; j++) inst.set(m.keys[j], m.map[m.keys[j]]); }
      return inst; // best-effort: VM-class constructor body is not run in the standalone VM
    }
    return null;
  }

  function host(name, args) {
    switch (name) {
      case 'len': return Array.isArray(args[0]) ? args[0].length : (isObj(args[0]) ? args[0].keys.length : String(args[0]).length);
      case 'str': return toStr(args[0]);
      case 'num': return parseFloat(args[0]);
      case 'floor': return Math.floor(args[0]);
      case 'abs': return Math.abs(args[0]);
      case 'rand': return Math.random();
      case 'time': return Date.now();
      case 'push': args[0].push(args[1]); return args[0];
      case 'keys': return isObj(args[0]) ? args[0].keys.slice() : (args[0] && typeof args[0] === 'object' ? Object.keys(args[0]) : []);
      case 'has': return isObj(args[0]) ? args[0].has(args[1]) : false;
      case '__setglobal': __globals[args[0]] = args[1]; return args[1];
      case '__getglobal': {
        var nm = args[0];
        if (Object.prototype.hasOwnProperty.call(__globals, nm)) return __globals[nm];
        if (nm === 'require') return __requireBridge;
        if (Object.prototype.hasOwnProperty.call(__hostg, nm)) return __hostg[nm];
        return undefined;
      }
      case 'typeof': return __typeof(args[0]);
      case 'bitnot': return ~(Number(args[0]) || 0);
      case 'pow': return Math.pow(args[0], args[1]);
      case 'instanceof': return __instanceof(args[0], args[1]);
      case 'inop': { var k = args[0], o = args[1]; if (isObj(o)) return o.has(k); if (Array.isArray(o)) return Number(k) >= 0 && Number(k) < o.length; if (o && typeof o === 'object') return k in o; return false; }
      case 'require': return __requireBridge(args[0]);
      case '__new': return __newObj(args);
      case '__regex': { try { return new RegExp(args[0], args[1] || ''); } catch (e) { return null; } }
      default: throw new Error('unknown host builtin ' + name);
    }
  }

  function run(prog) {
    var b2c = prog.byte2canon, consts = prog.consts, fns = prog.fns;
    var stack = [];
    var frames = [];
    var handlers = []; // { frame, framesLen, stackLen, addr }
    var frame = { fn: fns[0], ip: 0, locals: mkCells(fns[0].nlocals), upvals: [] };

    function rd8() { return frame.fn.code[frame.ip++]; }
    function rd16() { var lo = frame.fn.code[frame.ip], hi = frame.fn.code[frame.ip + 1]; frame.ip += 2; return lo | (hi << 8); }
    function raise(value) {
      while (handlers.length) {
        var h = handlers.pop();
        frames.length = h.framesLen;
        frame = h.frame;
        stack.length = h.stackLen;
        frame.ip = h.addr;
        stack.push(value);
        return true;
      }
      return false;
    }

    var steps = 0;
    for (;;) {
      if (MAX_STEPS && ++steps > MAX_STEPS) throw new Error('resource limit: instruction budget exceeded');
      var op = b2c[rd8()];
      {
        switch (op) {
          case OP.HALT: return;
          case OP.PUSH_CONST: stack.push(consts[rd16()]); break;
          case OP.PUSH_TRUE: stack.push(true); break;
          case OP.PUSH_FALSE: stack.push(false); break;
          case OP.PUSH_NULL: stack.push(null); break;
          case OP.POP: stack.pop(); break;
          case OP.DUP: stack.push(stack[stack.length - 1]); break;
          case OP.LOAD: stack.push(frame.locals[rd16()].v); break;
          case OP.STORE: frame.locals[rd16()].v = stack.pop(); break;
          case OP.LOAD_UP: stack.push(frame.upvals[rd16()].v); break;
          case OP.STORE_UP: frame.upvals[rd16()].v = stack.pop(); break;
          case OP.ADD: { var b = stack.pop(), a = stack.pop(); stack.push((typeof a === 'number' && typeof b === 'number') ? a + b : toStr(a) + toStr(b)); break; }
          case OP.SUB: { var b = stack.pop(), a = stack.pop(); stack.push(a - b); break; }
          case OP.MUL: { var b = stack.pop(), a = stack.pop(); stack.push(a * b); break; }
          case OP.DIV: { var b = stack.pop(), a = stack.pop(); stack.push(a / b); break; }
          case OP.MOD: { var b = stack.pop(), a = stack.pop(); stack.push(a % b); break; }
          case OP.NEG: stack.push(-stack.pop()); break;
          case OP.NOT: stack.push(!truthy(stack.pop())); break;
          case OP.EQ: { var b = stack.pop(), a = stack.pop(); stack.push(a === b); break; }
          case OP.NEQ: { var b = stack.pop(), a = stack.pop(); stack.push(a !== b); break; }
          case OP.LT: { var b = stack.pop(), a = stack.pop(); stack.push(a < b); break; }
          case OP.GT: { var b = stack.pop(), a = stack.pop(); stack.push(a > b); break; }
          case OP.LTE: { var b = stack.pop(), a = stack.pop(); stack.push(a <= b); break; }
          case OP.GTE: { var b = stack.pop(), a = stack.pop(); stack.push(a >= b); break; }
          case OP.BAND: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a & b)); break; }
          case OP.BOR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a | b)); break; }
          case OP.BXOR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a ^ b)); break; }
          case OP.SHL: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a << b)); break; }
          case OP.SHR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a >>> b)); break; }
          case OP.JMP: { frame.ip = rd16(); break; }
          case OP.JZ: { var addr = rd16(); if (!truthy(stack.pop())) frame.ip = addr; break; }
          case OP.JNZ: { var addr = rd16(); if (truthy(stack.pop())) frame.ip = addr; break; }
          case OP.CALL: {
            var fnIdx = rd16(), argc = rd8();
            if (MAX_DEPTH && frames.length + 1 > MAX_DEPTH) throw new Error('resource limit: call depth exceeded');
            var callee = fns[fnIdx];
            var locals = mkCells(callee.nlocals);
            for (var k = argc - 1; k >= 0; k--) locals[k].v = stack.pop();
            frames.push(frame);
            frame = { fn: callee, ip: 0, locals: locals, upvals: [] };
            break;
          }
          case OP.CALL_VALUE: {
            var vargc = rd8();
            if (MAX_DEPTH && frames.length + 1 > MAX_DEPTH) throw new Error('resource limit: call depth exceeded');
            var vargs = new Array(vargc);
            for (var vk = vargc - 1; vk >= 0; vk--) vargs[vk] = stack.pop();
            var vcallee = stack.pop();
            if (typeof vcallee === 'function' && !isClosure(vcallee)) { stack.push(vcallee.apply(null, vargs)); break; }
            if (!isClosure(vcallee)) throw new Error('value is not callable: ' + toStr(vcallee));
            var vfn = fns[vcallee.fn];
            var vlocals = mkCells(vfn.nlocals);
            for (var vk2 = 0; vk2 < vargc; vk2++) vlocals[vk2].v = vargs[vk2];
            frames.push(frame);
            frame = { fn: vfn, ip: 0, locals: vlocals, upvals: vcallee.upvals };
            break;
          }
          case OP.LOAD_THIS: { stack.push(frame.thisObj !== undefined ? frame.thisObj : null); break; }
          case OP.CALL_METHOD: {
            var margc = rd8();
            var margs = new Array(margc);
            for (var mk = margc - 1; mk >= 0; mk--) margs[mk] = stack.pop();
            var mcallee = stack.pop();
            var mrecv = stack.pop();
            if (typeof mcallee === 'function' && !isClosure(mcallee)) { stack.push(mcallee.apply(mrecv, margs)); break; }
            if (!isClosure(mcallee)) throw new Error('value is not callable: ' + toStr(mcallee));
            var mfn = fns[mcallee.fn];
            var mlocals = mkCells(mfn.nlocals);
            for (var mk2 = 0; mk2 < margc; mk2++) mlocals[mk2].v = margs[mk2];
            frames.push(frame);
            frame = { fn: mfn, ip: 0, locals: mlocals, upvals: mcallee.upvals, thisObj: mrecv };
            break;
          }
          case OP.AWAIT: { stack.push(stack.pop()); break; } // synchronous VM: best-effort passthrough
          case OP.CLOSE_UPVALUE: { rd16(); break; } // locals are already heap cells
          case OP.LOADADD: { var laI = rd16(); var laX = stack.pop(), laB = frame.locals[laI].v; stack.push((typeof laX === 'number' && typeof laB === 'number') ? laX + laB : toStr(laX) + toStr(laB)); break; }
          case OP.LOADSUB: { var lsI = rd16(); stack.push(stack.pop() - frame.locals[lsI].v); break; }
          case OP.LOADLT: { var llI = rd16(); stack.push(stack.pop() < frame.locals[llI].v); break; }
          case OP.CONSTADD: { var caI = rd16(); var caX = stack.pop(), caB = consts[caI]; stack.push((typeof caX === 'number' && typeof caB === 'number') ? caX + caB : toStr(caX) + toStr(caB)); break; }
          case OP.CLOSURE: {
            var cidx = rd16();
            var cfn = fns[cidx];
            var ups = new Array(cfn.upvals.length);
            for (var cu = 0; cu < cfn.upvals.length; cu++) { var d = cfn.upvals[cu]; ups[cu] = d.fromLocal ? frame.locals[d.index] : frame.upvals[d.index]; }
            stack.push({ __closure: true, fn: cidx, upvals: ups });
            break;
          }
          case OP.RET: {
            var rv = stack.pop();
            if (frames.length === 0) return rv;
            frame = frames.pop();
            stack.push(rv);
            break;
          }
          case OP.CALL_HOST: {
            var nameIdx = rd16(), hargc = rd8();
            var hargs = new Array(hargc);
            for (var j = hargc - 1; j >= 0; j--) hargs[j] = stack.pop();
            stack.push(host(consts[nameIdx], hargs));
            break;
          }
          case OP.NEW_ARR: {
            var n = rd16(), arr = new Array(n);
            for (var m = n - 1; m >= 0; m--) arr[m] = stack.pop();
            stack.push(arr);
            break;
          }
          case OP.NEW_OBJ: {
            var on = rd16(), pairs = [];
            for (var om = 0; om < on; om++) { var ov = stack.pop(), ok = stack.pop(); pairs.push([ok, ov]); }
            pairs.reverse();
            var obj = new VMObj();
            for (var pi = 0; pi < pairs.length; pi++) obj.set(pairs[pi][0], pairs[pi][1]);
            stack.push(obj);
            break;
          }
          case OP.ARR_GET: { var idx = stack.pop(), arr2 = stack.pop(); stack.push(idxGet(arr2, idx)); break; }
          case OP.ARR_SET: { var val = stack.pop(), idx2 = stack.pop(), arr3 = stack.pop(); idxSet(arr3, idx2, val); stack.push(val); break; }
          case OP.TRY: { handlers.push({ frame: frame, framesLen: frames.length, stackLen: stack.length, addr: rd16() }); break; }
          case OP.END_TRY: { handlers.pop(); break; }
          case OP.THROW: { var tv = stack.pop(); if (!raise(tv)) throw new Error('uncaught exception: ' + toStr(tv)); break; }
          case OP.PRINT: { var out = (typeof process !== 'undefined' && process.stdout) ? function (s) { process.stdout.write(s + '\n'); } : console.log; out(toStr(stack.pop())); break; }
          default: throw new Error('illegal opcode ' + op + ' at ip=' + (frame.ip - 1));
        }
      }
    }
  }

  try {
    run(load());
  } catch (e) {
    if (typeof console !== 'undefined') console.error('[vm-gen] ' + e.message);
    if (typeof process !== 'undefined' && process.exit) process.exit(1);
  }
})();
