'use strict';
// Emit a standalone Lua 5.1+ VM that embeds and executes a protected image.
// Mirrors emit-js.js exactly at the algorithm level. Uses 0-based byte tables
// so all index arithmetic matches the JS reference implementation, and pure-Lua
// base64 / bitwise helpers so it runs with no external libraries.

const { OP_NAME } = require('./opcodes');
const V = require('./version');

function opConstBlockLua() {
  return OP_NAME.map((n, i) => `  ${n} = ${i}`).join(',\n');
}

function emitLua(image, opts = {}) {
  const b64 = Buffer.from(image).toString('base64');
  const banner = opts.banner !== false;
  const maxSteps = opts.maxSteps | 0;
  const maxDepth = opts.maxDepth | 0;

  return `${banner ? `-- Generated by vm-gen -- standalone protected Lua VM.
-- Do not edit: the embedded image is integrity-checked at startup.
` : ''}local IMAGE_B64 = ${JSON.stringify(b64)}

local OP = {
${opConstBlockLua()}
}

local FORMAT_MAJOR = ${V.FORMAT_MAJOR}
local EXPECTED_OPCOUNT = ${OP_NAME.length}
local MAX_STEPS = ${maxSteps}
local MAX_DEPTH = ${maxDepth}
local SALT = ${(opts.salt >>> 0)}

local MASK32 = 4294967296
local floor = math.floor

-- 32-bit xor (used to recover the hidden master seed from the stored value)
local function bxor32(a, b)
  local r, bit = 0, 1
  for _ = 1, 32 do
    if (a % 2) ~= (b % 2) then r = r + bit end
    a = floor(a / 2); b = floor(b / 2); bit = bit * 2
  end
  return r
end

local function mul32(a, b)
  a = a % MASK32; b = b % MASK32
  local ah = floor(a / 65536); local al = a % 65536
  local r = ((ah * b) % 65536) * 65536 + al * b
  return r % MASK32
end
local function lcgNext(s) return (mul32(s, 1664525) + 1013904223) % MASK32 end
local function ksByte(s) return floor(s / 16777216) % 256 end
local function fnSeed(codeSeed, idx) return (codeSeed + mul32(idx, 2654435761)) % MASK32 end
local function roundSeed(cs, idx, r) if r == 0 then return fnSeed(cs, idx) else return (fnSeed(cs, idx) + mul32(r, 2246822519)) % MASK32 end end

-- byte-wise xor (both < 256)
local function bxor8(a, b)
  local r, bit = 0, 1
  for _ = 1, 8 do
    local abit = a % 2; local bbit = b % 2
    if abit ~= bbit then r = r + bit end
    a = floor(a / 2); b = floor(b / 2); bit = bit * 2
  end
  return r
end

-- cipher over a 0-based byte table {len=n, [0..n-1]}
local function cipher(bytes, seed)
  local st = seed % MASK32
  local out = { len = bytes.len }
  for i = 0, bytes.len - 1 do
    st = lcgNext(st)
    out[i] = bxor8(bytes[i], ksByte(st))
  end
  return out
end

local function decRounds(bytes, cs, idx, rounds)
  local out = bytes
  for r = 0, rounds - 1 do out = cipher(out, roundSeed(cs, idx, r)) end
  return out
end

local function fnv1a(bytes)
  local h = 2166136261
  for i = 0, bytes.len - 1 do
    local low = h % 256
    h = h - low + bxor8(low, bytes[i])
    h = mul32(h, 16777619)
  end
  return h % MASK32
end

-- keyed MAC (matches protect.keyedMac): two FNV-1a passes with the key mixed in.
local function concatBytes(a, b)
  local out = { len = a.len + b.len }
  for i = 0, a.len - 1 do out[i] = a[i] end
  for i = 0, b.len - 1 do out[a.len + i] = b[i] end
  return out
end
local function keyedMac(keyBytes, bytes)
  local m1 = fnv1a(concatBytes(keyBytes, bytes))
  local suffix = { len = 4 }; suffix[0] = 0x9e; suffix[1] = 0x37; suffix[2] = 0x79; suffix[3] = 0xb9
  local m2 = fnv1a(concatBytes(concatBytes(bytes, keyBytes), suffix))
  local out = { len = 8 }
  out[0] = m1 % 256; out[1] = floor(m1 / 256) % 256; out[2] = floor(m1 / 65536) % 256; out[3] = floor(m1 / 16777216) % 256
  out[4] = m2 % 256; out[5] = floor(m2 / 256) % 256; out[6] = floor(m2 / 65536) % 256; out[7] = floor(m2 / 16777216) % 256
  return out
end
local function strBytes(s)
  local t = { len = #s }
  for i = 1, #s do t[i - 1] = string.byte(s, i) end
  return t
end
local function envKey()
  local ok, v = pcall(function() return os.getenv('VMGEN_KEY') end)
  if ok and v then return v else return '' end
end

-- base64 -> 0-based byte table
local B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local B64INV = {}
for i = 1, #B64 do B64INV[B64:sub(i, i)] = i - 1 end
local function decodeB64(s)
  local out = { len = 0 }
  local n = 0
  local acc, bits = 0, 0
  for i = 1, #s do
    local ch = s:sub(i, i)
    if ch == '=' then break end
    local v = B64INV[ch]
    if v ~= nil then
      acc = acc * 64 + v
      bits = bits + 6
      if bits >= 8 then
        bits = bits - 8
        local byte = floor(acc / (2 ^ bits)) % 256
        out[n] = byte; n = n + 1
      end
    end
  end
  out.len = n
  return out
end

-- 0-based byte table -> Lua string
local function bytesToStr(bytes, from, len)
  local chars = {}
  for i = 0, len - 1 do chars[i + 1] = string.char(bytes[from + i]) end
  return table.concat(chars)
end

-- ---- parse + verify image ----
local function load()
  local b = decodeB64(IMAGE_B64)
  if b[0] ~= 0x56 or b[1] ~= 0x47 then error('bad magic') end
  local major = b[2] -- b[3]=minor b[4]=flags b[5]=profile b[6]=arch
  if major ~= FORMAT_MAJOR then error('unsupported image format major ' .. major) end
  local checksum = b[7] + b[8] * 256 + b[9] * 65536 + b[10] * 16777216
  -- domain table: 4x u32 at bytes 11..26 (header, dispatch, const, fn).
  -- Normalize with % MASK32 so a Lua build with 32-bit integers (which would
  -- wrap a >2^31 checksum negative) still compares equal to fnv1a's result.
  local function d32(o) return (b[o] + b[o + 1] * 256 + b[o + 2] * 65536 + b[o + 3] * 16777216) % MASK32 end
  local dHeader = d32(11); local dDispatch = d32(15); local dConst = d32(19); local dFn = d32(23)
  local SIGNED = (floor(b[4] / 4) % 2) == 1
  local sigBytes, bodyStart
  if SIGNED then
    sigBytes = { len = 8 }; for i = 0, 7 do sigBytes[i] = b[27 + i] end
    bodyStart = 35
  else
    sigBytes = { len = 0 }; bodyStart = 27
  end
  local body = { len = b.len - bodyStart }
  for i = 0, body.len - 1 do body[i] = b[i + bodyStart] end
  -- master integrity: header meta(5) + domain table(16) + optional signature + body
  local sl = sigBytes.len
  local chk = { len = 21 + sl + body.len }
  chk[0] = b[2]; chk[1] = b[3]; chk[2] = b[4]; chk[3] = b[5]; chk[4] = b[6]
  for i = 0, 15 do chk[5 + i] = b[11 + i] end
  for i = 0, sl - 1 do chk[21 + i] = sigBytes[i] end
  for i = 0, body.len - 1 do chk[21 + sl + i] = body[i] end
  if fnv1a(chk) ~= (checksum % MASK32) then error('integrity check failed: image tampered') end
  -- independent domain: header
  local metaChk = { len = 5 }; metaChk[0] = b[2]; metaChk[1] = b[3]; metaChk[2] = b[4]; metaChk[3] = b[5]; metaChk[4] = b[6]
  if fnv1a(metaChk) ~= dHeader then error('integrity check failed: header domain') end
  -- authenticity / entitlement: verify the keyed signature against a runtime key
  if SIGNED then
    local mac = keyedMac(strBytes(envKey()), body)
    local ok = true
    for i = 0, 7 do if mac[i] ~= sigBytes[i] then ok = false end end
    if not ok then error('authenticity/authorization check failed') end
  end

  local p = 0
  local function u8() local v = body[p]; p = p + 1; return v end
  local function u16() local v = body[p] + body[p + 1] * 256; p = p + 2; return v end
  local function u32() local v = body[p] + body[p + 1] * 256 + body[p + 2] * 65536 + body[p + 3] * 16777216; p = p + 4; return v end

  -- Regenerate cipher seeds + opcode permutation from the hidden master seed
  -- (none are stored in the image); mirrors the builder and emit-js exactly.
  local obfMaster = u32()
  local masterSeed = bxor32(obfMaster, SALT)
  local numCanon = u8()
  if numCanon ~= EXPECTED_OPCOUNT then error('integrity check failed: VM/opcode-table mismatch') end
  local rs = masterSeed; if rs == 0 then rs = 2654435769 end
  local function rng() rs = lcgNext(rs); return rs end
  local pool = {}
  for i = 0, 255 do pool[i] = i end
  for j = 255, 1, -1 do local jj = rng() % (j + 1); local tt = pool[j]; pool[j] = pool[jj]; pool[jj] = tt end
  local identPerm = (floor(b[4] / 8) % 2) == 1
  local byte2canon = {}
  local permBytes = { len = numCanon }
  for i = 0, numCanon - 1 do local pb; if identPerm then pb = i else pb = pool[i] end; byte2canon[pb] = i; permBytes[i] = pb end
  local codeSeed = rng() % MASK32
  local constSeed = rng() % MASK32
  -- independent domain: dispatch (opcode permutation)
  if fnv1a(permBytes) ~= dDispatch then error('integrity check failed: dispatch domain') end

  local constCount = u16()
  local encConstLen = u32()
  local encConst = { len = encConstLen }
  for i = 0, encConstLen - 1 do encConst[i] = body[p + i] end
  p = p + encConstLen
  -- independent domain: constants
  if fnv1a(encConst) ~= dConst then error('integrity check failed: constant domain') end
  local constBlob = cipher(encConst, constSeed)

  local consts = {}
  local cp = 0
  for c = 0, constCount - 1 do
    local tag = constBlob[cp]; cp = cp + 1
    if tag == 2 then
      -- concealed integer: recover A xor B, xored byte-by-byte (bxor8 is in scope)
      local v = 0
      for bi = 0, 3 do
        local x = bxor8(constBlob[cp + bi], constBlob[cp + 4 + bi])
        v = v + x * (256 ^ bi)
      end
      cp = cp + 8
      consts[c] = v
    else
      local len = constBlob[cp] + constBlob[cp + 1] * 256; cp = cp + 2
      local str = bytesToStr(constBlob, cp, len); cp = cp + len
      if tag == 0 then consts[c] = tonumber(str) else consts[c] = str end
    end
  end

  local fnCount = u16()
  local fns = {}
  local fnAll = { len = 0 }
  for f = 0, fnCount - 1 do
    local nl = u8()
    local name = bytesToStr(body, p, nl); p = p + nl
    local nparams = u8()
    local nlocals = u16()
    local nUp = u8()
    local upvals = { n = nUp }
    for uu = 0, nUp - 1 do local fl = u8(); local ui = u16(); upvals[uu] = { fromLocal = (fl == 1), index = ui } end
    local protLevel = u8()
    local codeLen = u32()
    local enc = { len = codeLen }
    for i = 0, codeLen - 1 do enc[i] = body[p + i] end
    p = p + codeLen
    for i = 0, codeLen - 1 do fnAll[fnAll.len + i] = enc[i] end
    fnAll.len = fnAll.len + codeLen
    fns[f] = { name = name, nparams = nparams, nlocals = nlocals, upvals = upvals, code = decRounds(enc, codeSeed, f, protLevel) }
  end
  -- independent domain: functions
  if fnv1a(fnAll) ~= dFn then error('integrity check failed: function domain') end
  return { byte2canon = byte2canon, consts = consts, fns = fns }
end

-- ---- runtime values: NULL | number | string | boolean | array | object | closure | cell ----
local NULL = setmetatable({}, { __tostring = function() return 'null' end })
local function newArr(n) return { __arr = true, n = n } end
local function isArr(v) return type(v) == 'table' and v.__arr == true end
local function mkCells(n) local a = {} for i = 0, n - 1 do a[i] = { v = NULL } end return a end
local function newObj() return { __obj = true, keys = { n = 0 }, map = {} } end
local function isObj(v) return type(v) == 'table' and v.__obj == true end
local function isClosure(v) return type(v) == 'table' and v.__closure == true end
local function objSet(o, k, v) k = tostring(k); if o.map[k] == nil then o.keys.n = o.keys.n + 1; o.keys[o.keys.n] = k end; o.map[k] = v end
local function objGet(o, k) k = tostring(k); local v = o.map[k]; if v == nil then return NULL else return v end end
local function objHas(o, k) return o.map[tostring(k)] ~= nil end

local function toStr(v)
  if v == NULL then return 'null' end
  if v == true then return 'true' end
  if v == false then return 'false' end
  if type(v) == 'number' then
    if v == floor(v) and v > -1e15 and v < 1e15 then return string.format('%d', v) end
    return tostring(v)
  end
  if isArr(v) then
    local parts = {}
    for i = 0, v.n - 1 do parts[i + 1] = toStr(v[i]) end
    return '[' .. table.concat(parts, ', ') .. ']'
  end
  if isObj(v) then
    local parts = {}
    for i = 1, v.keys.n do local k = v.keys[i]; parts[i] = k .. ': ' .. toStr(v.map[k]) end
    return '{' .. table.concat(parts, ', ') .. '}'
  end
  if isClosure(v) then return '<fn>' end
  return tostring(v)
end

local function truthy(v)
  return v ~= NULL and v ~= false and v ~= 0 and v ~= ''
end

-- unsigned 32-bit bitwise helpers
local function band(a, b) local r, bit = 0, 1; for _ = 1, 32 do if (a % 2 == 1) and (b % 2 == 1) then r = r + bit end; a = floor(a / 2); b = floor(b / 2); bit = bit * 2 end; return r end
local function bor(a, b) local r, bit = 0, 1; for _ = 1, 32 do if (a % 2 == 1) or (b % 2 == 1) then r = r + bit end; a = floor(a / 2); b = floor(b / 2); bit = bit * 2 end; return r end
local function bxor(a, b) local r, bit = 0, 1; for _ = 1, 32 do local x = (a % 2 + b % 2) % 2; if x == 1 then r = r + bit end; a = floor(a / 2); b = floor(b / 2); bit = bit * 2 end; return r end
local function shl(a, b) return (a * (2 ^ b)) % MASK32 end
local function shr(a, b) return floor(a / (2 ^ b)) end

local function idxGet(obj, key)
  if isObj(obj) then return objGet(obj, key)
  elseif isArr(obj) then local r = obj[key]; if r == nil then return NULL else return r end
  elseif type(obj) == 'string' then return string.sub(obj, key + 1, key + 1)
  else error('cannot index ' .. toStr(obj)) end
end
local function idxSet(obj, key, val)
  if isObj(obj) then objSet(obj, key, val)
  elseif isArr(obj) then obj[key] = val; if key + 1 > obj.n then obj.n = key + 1 end
  else error('cannot assign index of ' .. toStr(obj)) end
end

local globals = {}
local function host(name, args)
  if name == '__setglobal' then globals[args[0]] = args[1]; return args[1]
  elseif name == '__getglobal' then local v = globals[args[0]]; if v == nil then return NULL else return v end
  elseif name == 'typeof' then local v = args[0]; if v == nil or v == NULL then return 'undefined' elseif type(v) == 'number' then return 'number' elseif type(v) == 'string' then return 'string' elseif type(v) == 'boolean' then return 'boolean' else return 'object' end
  elseif name == 'bitnot' then return -1 - (tonumber(args[0]) or 0)
  elseif name == 'pow' then return (tonumber(args[0]) or 0) ^ (tonumber(args[1]) or 0)
  elseif name == 'instanceof' then return false
  elseif name == 'inop' then return false
  elseif name == 'require' then return NULL
  elseif name == '__new' then return NULL
  elseif name == '__regex' then return NULL
  elseif name == 'len' then local a = args[0]; if isArr(a) then return a.n elseif isObj(a) then return a.keys.n else return #tostring(a) end
  elseif name == 'str' then return toStr(args[0])
  elseif name == 'num' then return tonumber(args[0])
  elseif name == 'floor' then return floor(args[0])
  elseif name == 'abs' then return math.abs(args[0])
  elseif name == 'rand' then return math.random()
  elseif name == 'time' then return os.time() * 1000
  elseif name == 'push' then local a = args[0]; a[a.n] = args[1]; a.n = a.n + 1; return a
  elseif name == 'keys' then local a = args[0]; if isObj(a) then local arr = newArr(a.keys.n); for i = 1, a.keys.n do arr[i - 1] = a.keys[i] end; return arr else return newArr(0) end
  elseif name == 'has' then local a = args[0]; if isObj(a) then return objHas(a, args[1]) else return false end
  else error('unknown host builtin ' .. name) end
end

local function run(prog)
  local b2c, consts, fns = prog.byte2canon, prog.consts, prog.fns
  local stack, sp = {}, 0
  local frames, fp = {}, 0
  local handlers, hp = {}, 0

  local code, ip
  local frame = { code = fns[0].code, ip = 0, locals = mkCells(fns[0].nlocals), upvals = {} }
  code = frame.code; ip = frame.ip

  local function push(v) sp = sp + 1; stack[sp] = v end
  local function pop() local v = stack[sp]; stack[sp] = nil; sp = sp - 1; return v end

  local function rd8() local v = code[ip]; ip = ip + 1; return v end
  local function rd16() local v = code[ip] + code[ip + 1] * 256; ip = ip + 2; return v end

  -- unwind the call/operand stacks to the nearest handler; false if uncaught
  local function raise(value)
    if hp == 0 then return false end
    local h = handlers[hp]; handlers[hp] = nil; hp = hp - 1
    while fp > h.framesLen do frames[fp] = nil; fp = fp - 1 end
    frame = h.frame; code = frame.code; ip = h.addr
    while sp > h.stackLen do stack[sp] = nil; sp = sp - 1 end
    push(value)
    return true
  end

  local steps = 0
  while true do
    if MAX_STEPS > 0 then steps = steps + 1; if steps > MAX_STEPS then error('resource limit: instruction budget exceeded') end end
    local op = b2c[rd8()]
    if op == OP.HALT then return
    elseif op == OP.PUSH_CONST then push(consts[rd16()])
    elseif op == OP.PUSH_TRUE then push(true)
    elseif op == OP.PUSH_FALSE then push(false)
    elseif op == OP.PUSH_NULL then push(NULL)
    elseif op == OP.POP then pop()
    elseif op == OP.DUP then push(stack[sp])
    elseif op == OP.LOAD then push(frame.locals[rd16()].v)
    elseif op == OP.STORE then frame.locals[rd16()].v = pop()
    elseif op == OP.LOAD_UP then push(frame.upvals[rd16()].v)
    elseif op == OP.STORE_UP then frame.upvals[rd16()].v = pop()
    elseif op == OP.ADD then local b = pop(); local a = pop(); if type(a) == 'number' and type(b) == 'number' then push(a + b) else push(toStr(a) .. toStr(b)) end
    elseif op == OP.SUB then local b = pop(); local a = pop(); push(a - b)
    elseif op == OP.MUL then local b = pop(); local a = pop(); push(a * b)
    elseif op == OP.DIV then local b = pop(); local a = pop(); push(a / b)
    elseif op == OP.MOD then local b = pop(); local a = pop(); push(a % b)
    elseif op == OP.NEG then push(-pop())
    elseif op == OP.NOT then push(not truthy(pop()))
    elseif op == OP.EQ then local b = pop(); local a = pop(); push(a == b)
    elseif op == OP.NEQ then local b = pop(); local a = pop(); push(a ~= b)
    elseif op == OP.LT then local b = pop(); local a = pop(); push(a < b)
    elseif op == OP.GT then local b = pop(); local a = pop(); push(a > b)
    elseif op == OP.LTE then local b = pop(); local a = pop(); push(a <= b)
    elseif op == OP.GTE then local b = pop(); local a = pop(); push(a >= b)
    elseif op == OP.BAND then local b = pop(); local a = pop(); push(band(a, b))
    elseif op == OP.BOR then local b = pop(); local a = pop(); push(bor(a, b))
    elseif op == OP.BXOR then local b = pop(); local a = pop(); push(bxor(a, b))
    elseif op == OP.SHL then local b = pop(); local a = pop(); push(shl(a, b))
    elseif op == OP.SHR then local b = pop(); local a = pop(); push(shr(a, b))
    elseif op == OP.JMP then ip = rd16()
    elseif op == OP.JZ then local addr = rd16(); if not truthy(pop()) then ip = addr end
    elseif op == OP.JNZ then local addr = rd16(); if truthy(pop()) then ip = addr end
    elseif op == OP.CALL then
      local fnIdx = rd16(); local argc = rd8()
      if MAX_DEPTH > 0 and fp + 1 > MAX_DEPTH then error('resource limit: call depth exceeded') end
      local callee = fns[fnIdx]
      local locals = mkCells(callee.nlocals)
      for k = argc - 1, 0, -1 do locals[k].v = pop() end
      frame.ip = ip
      fp = fp + 1; frames[fp] = frame
      frame = { code = callee.code, ip = 0, locals = locals, upvals = {} }
      code = frame.code; ip = 0
    elseif op == OP.CALL_VALUE then
      local vargc = rd8()
      if MAX_DEPTH > 0 and fp + 1 > MAX_DEPTH then error('resource limit: call depth exceeded') end
      local vargs = {}
      for k = vargc - 1, 0, -1 do vargs[k] = pop() end
      local vcallee = pop()
      if not isClosure(vcallee) then error('value is not callable: ' .. toStr(vcallee)) end
      local vfn = fns[vcallee.fn]
      local locals = mkCells(vfn.nlocals)
      for k = 0, vargc - 1 do locals[k].v = vargs[k] end
      frame.ip = ip
      fp = fp + 1; frames[fp] = frame
      frame = { code = vfn.code, ip = 0, locals = locals, upvals = vcallee.upvals }
      code = frame.code; ip = 0
    elseif op == OP.CLOSURE then
      local cidx = rd16()
      local cfn = fns[cidx]
      local ups = { n = cfn.upvals.n }
      for u = 0, cfn.upvals.n - 1 do
        local d = cfn.upvals[u]
        if d.fromLocal then ups[u] = frame.locals[d.index] else ups[u] = frame.upvals[d.index] end
      end
      push({ __closure = true, fn = cidx, upvals = ups })
    elseif op == OP.RET then
      local rv = pop()
      if fp == 0 then return rv end
      frame = frames[fp]; frames[fp] = nil; fp = fp - 1
      code = frame.code; ip = frame.ip
      push(rv)
    elseif op == OP.CALL_HOST then
      local nameIdx = rd16(); local hargc = rd8()
      local hargs = {}
      for j = hargc - 1, 0, -1 do hargs[j] = pop() end
      push(host(consts[nameIdx], hargs))
    elseif op == OP.NEW_ARR then
      local n = rd16(); local arr = newArr(n)
      for m = n - 1, 0, -1 do arr[m] = pop() end
      push(arr)
    elseif op == OP.NEW_OBJ then
      local n = rd16()
      local collected = {}
      for m = 1, n do local v = pop(); local k = pop(); collected[m] = { k, v } end
      local obj = newObj()
      for m = n, 1, -1 do objSet(obj, collected[m][1], collected[m][2]) end
      push(obj)
    elseif op == OP.ARR_GET then local key = pop(); local obj = pop(); push(idxGet(obj, key))
    elseif op == OP.ARR_SET then local val = pop(); local key = pop(); local obj = pop(); idxSet(obj, key, val); push(val)
    elseif op == OP.TRY then local addr = rd16(); hp = hp + 1; handlers[hp] = { frame = frame, framesLen = fp, stackLen = sp, addr = addr }
    elseif op == OP.END_TRY then handlers[hp] = nil; hp = hp - 1
    elseif op == OP.THROW then local tv = pop(); if not raise(tv) then error('uncaught exception: ' .. toStr(tv)) end
    elseif op == OP.PRINT then print(toStr(pop()))
    else error('illegal opcode ' .. tostring(op)) end
  end
end

local ok, err = pcall(function() run(load()) end)
if not ok then
  io.stderr:write('[vm-gen] ' .. tostring(err) .. '\\n')
  os.exit(1)
end
`;
}

module.exports = { emitLua };
