'use strict';
// Emit a standalone Lua 5.1+ VM that embeds and executes a protected image.
// Mirrors emit-js.js exactly at the algorithm level. Uses 0-based byte tables
// so all index arithmetic matches the JS reference implementation, and pure-Lua
// base64 / bitwise helpers so it runs with no external libraries.

const { OP_NAME } = require('./opcodes');

function opConstBlockLua() {
  return OP_NAME.map((n, i) => `  ${n} = ${i}`).join(',\n');
}

function emitLua(image, opts = {}) {
  const b64 = Buffer.from(image).toString('base64');
  const banner = opts.banner !== false;

  return `${banner ? `-- Generated by vm-gen -- standalone protected Lua VM.
-- Do not edit: the embedded image is integrity-checked at startup.
` : ''}local IMAGE_B64 = ${JSON.stringify(b64)}

local OP = {
${opConstBlockLua()}
}

local MASK32 = 4294967296
local floor = math.floor

local function mul32(a, b)
  a = a % MASK32; b = b % MASK32
  local ah = floor(a / 65536); local al = a % 65536
  local r = ((ah * b) % 65536) * 65536 + al * b
  return r % MASK32
end
local function lcgNext(s) return (mul32(s, 1664525) + 1013904223) % MASK32 end
local function ksByte(s) return floor(s / 16777216) % 256 end
local function fnSeed(codeSeed, idx) return (codeSeed + mul32(idx, 2654435761)) % MASK32 end

-- byte-wise xor (both < 256)
local function bxor8(a, b)
  local r, bit = 0, 1
  for _ = 1, 8 do
    local abit = a % 2; local bbit = b % 2
    if abit ~= bbit then r = r + bit end
    a = floor(a / 2); b = floor(b / 2); bit = bit * 2
  end
  return r
end

-- cipher over a 0-based byte table {len=n, [0..n-1]}
local function cipher(bytes, seed)
  local st = seed % MASK32
  local out = { len = bytes.len }
  for i = 0, bytes.len - 1 do
    st = lcgNext(st)
    out[i] = bxor8(bytes[i], ksByte(st))
  end
  return out
end

local function fnv1a(bytes)
  local h = 2166136261
  for i = 0, bytes.len - 1 do
    local low = h % 256
    h = h - low + bxor8(low, bytes[i])
    h = mul32(h, 16777619)
  end
  return h % MASK32
end

-- base64 -> 0-based byte table
local B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local B64INV = {}
for i = 1, #B64 do B64INV[B64:sub(i, i)] = i - 1 end
local function decodeB64(s)
  local out = { len = 0 }
  local n = 0
  local acc, bits = 0, 0
  for i = 1, #s do
    local ch = s:sub(i, i)
    if ch == '=' then break end
    local v = B64INV[ch]
    if v ~= nil then
      acc = acc * 64 + v
      bits = bits + 6
      if bits >= 8 then
        bits = bits - 8
        local byte = floor(acc / (2 ^ bits)) % 256
        out[n] = byte; n = n + 1
      end
    end
  end
  out.len = n
  return out
end

-- 0-based byte table -> Lua string
local function bytesToStr(bytes, from, len)
  local chars = {}
  for i = 0, len - 1 do chars[i + 1] = string.char(bytes[from + i]) end
  return table.concat(chars)
end

-- ---- parse + verify image ----
local function load()
  local b = decodeB64(IMAGE_B64)
  if b[0] ~= 0x56 or b[1] ~= 0x47 then error('bad magic') end
  if b[2] ~= 1 then error('bad version') end
  local checksum = b[3] + b[4] * 256 + b[5] * 65536 + b[6] * 16777216
  local body = { len = b.len - 7 }
  for i = 0, body.len - 1 do body[i] = b[i + 7] end
  if fnv1a(body) ~= (checksum % MASK32) then error('integrity check failed: image tampered') end

  local p = 0
  local function u8() local v = body[p]; p = p + 1; return v end
  local function u16() local v = body[p] + body[p + 1] * 256; p = p + 2; return v end
  local function u32() local v = body[p] + body[p + 1] * 256 + body[p + 2] * 65536 + body[p + 3] * 16777216; p = p + 4; return v end

  local codeSeed = u32(); local constSeed = u32()
  local numCanon = u8()
  local byte2canon = {}
  for i = 0, numCanon - 1 do byte2canon[u8()] = i end

  local constCount = u16()
  local encConstLen = u32()
  local encConst = { len = encConstLen }
  for i = 0, encConstLen - 1 do encConst[i] = body[p + i] end
  p = p + encConstLen
  local constBlob = cipher(encConst, constSeed)

  local consts = {}
  local cp = 0
  for c = 0, constCount - 1 do
    local tag = constBlob[cp]; cp = cp + 1
    local len = constBlob[cp] + constBlob[cp + 1] * 256; cp = cp + 2
    local str = bytesToStr(constBlob, cp, len); cp = cp + len
    if tag == 0 then consts[c] = tonumber(str) else consts[c] = str end
  end

  local fnCount = u16()
  local fns = {}
  for f = 0, fnCount - 1 do
    local nl = u8()
    local name = bytesToStr(body, p, nl); p = p + nl
    local nparams = u8()
    local nlocals = u16()
    local codeLen = u32()
    local enc = { len = codeLen }
    for i = 0, codeLen - 1 do enc[i] = body[p + i] end
    p = p + codeLen
    fns[f] = { name = name, nparams = nparams, nlocals = nlocals, code = cipher(enc, fnSeed(codeSeed, f)) }
  end
  return { byte2canon = byte2canon, consts = consts, fns = fns }
end

-- ---- runtime values ----
local NULL = setmetatable({}, { __tostring = function() return 'null' end })
local function newArr(n) return { __arr = true, n = n } end
local function isArr(v) return type(v) == 'table' and v.__arr == true end

local function toStr(v)
  if v == NULL then return 'null' end
  if v == true then return 'true' end
  if v == false then return 'false' end
  if type(v) == 'number' then
    if v == floor(v) and v > -1e15 and v < 1e15 then return string.format('%d', v) end
    return tostring(v)
  end
  if isArr(v) then
    local parts = {}
    for i = 0, v.n - 1 do parts[i + 1] = toStr(v[i]) end
    return '[' .. table.concat(parts, ', ') .. ']'
  end
  return tostring(v)
end

local function truthy(v)
  return v ~= NULL and v ~= false and v ~= 0 and v ~= ''
end

-- unsigned 32-bit bitwise helpers
local function band(a, b) local r, bit = 0, 1; for _ = 1, 32 do if (a % 2 == 1) and (b % 2 == 1) then r = r + bit end; a = floor(a / 2); b = floor(b / 2); bit = bit * 2 end; return r end
local function bor(a, b) local r, bit = 0, 1; for _ = 1, 32 do if (a % 2 == 1) or (b % 2 == 1) then r = r + bit end; a = floor(a / 2); b = floor(b / 2); bit = bit * 2 end; return r end
local function bxor(a, b) local r, bit = 0, 1; for _ = 1, 32 do local x = (a % 2 + b % 2) % 2; if x == 1 then r = r + bit end; a = floor(a / 2); b = floor(b / 2); bit = bit * 2 end; return r end
local function shl(a, b) return (a * (2 ^ b)) % MASK32 end
local function shr(a, b) return floor(a / (2 ^ b)) end

local function host(name, args)
  if name == 'len' then local a = args[0]; if isArr(a) then return a.n else return #tostring(a) end
  elseif name == 'str' then return toStr(args[0])
  elseif name == 'num' then return tonumber(args[0])
  elseif name == 'floor' then return floor(args[0])
  elseif name == 'abs' then return math.abs(args[0])
  elseif name == 'rand' then return math.random()
  elseif name == 'time' then return os.time() * 1000
  elseif name == 'push' then local a = args[0]; a[a.n] = args[1]; a.n = a.n + 1; return a
  else error('unknown host builtin ' .. name) end
end

local function run(prog)
  local b2c, consts, fns = prog.byte2canon, prog.consts, prog.fns
  local stack, sp = {}, 0
  local frames, fp = {}, 0

  local code, ip
  local frame = { code = fns[0].code, ip = 0, locals = {} }
  for i = 0, fns[0].nlocals - 1 do frame.locals[i] = NULL end
  code = frame.code; ip = frame.ip

  local function push(v) sp = sp + 1; stack[sp] = v end
  local function pop() local v = stack[sp]; stack[sp] = nil; sp = sp - 1; return v end

  local function rd8() local v = code[ip]; ip = ip + 1; return v end
  local function rd16() local v = code[ip] + code[ip + 1] * 256; ip = ip + 2; return v end

  while true do
    local op = b2c[rd8()]
    if op == OP.HALT then return
    elseif op == OP.PUSH_CONST then push(consts[rd16()])
    elseif op == OP.PUSH_TRUE then push(true)
    elseif op == OP.PUSH_FALSE then push(false)
    elseif op == OP.PUSH_NULL then push(NULL)
    elseif op == OP.POP then pop()
    elseif op == OP.DUP then push(stack[sp])
    elseif op == OP.LOAD then push(frame.locals[rd16()])
    elseif op == OP.STORE then frame.locals[rd16()] = pop()
    elseif op == OP.ADD then local b = pop(); local a = pop(); if type(a) == 'number' and type(b) == 'number' then push(a + b) else push(toStr(a) .. toStr(b)) end
    elseif op == OP.SUB then local b = pop(); local a = pop(); push(a - b)
    elseif op == OP.MUL then local b = pop(); local a = pop(); push(a * b)
    elseif op == OP.DIV then local b = pop(); local a = pop(); push(a / b)
    elseif op == OP.MOD then local b = pop(); local a = pop(); push(a % b)
    elseif op == OP.NEG then push(-pop())
    elseif op == OP.NOT then push(not truthy(pop()))
    elseif op == OP.EQ then local b = pop(); local a = pop(); push(a == b)
    elseif op == OP.NEQ then local b = pop(); local a = pop(); push(a ~= b)
    elseif op == OP.LT then local b = pop(); local a = pop(); push(a < b)
    elseif op == OP.GT then local b = pop(); local a = pop(); push(a > b)
    elseif op == OP.LTE then local b = pop(); local a = pop(); push(a <= b)
    elseif op == OP.GTE then local b = pop(); local a = pop(); push(a >= b)
    elseif op == OP.BAND then local b = pop(); local a = pop(); push(band(a, b))
    elseif op == OP.BOR then local b = pop(); local a = pop(); push(bor(a, b))
    elseif op == OP.BXOR then local b = pop(); local a = pop(); push(bxor(a, b))
    elseif op == OP.SHL then local b = pop(); local a = pop(); push(shl(a, b))
    elseif op == OP.SHR then local b = pop(); local a = pop(); push(shr(a, b))
    elseif op == OP.JMP then ip = rd16()
    elseif op == OP.JZ then local addr = rd16(); if not truthy(pop()) then ip = addr end
    elseif op == OP.JNZ then local addr = rd16(); if truthy(pop()) then ip = addr end
    elseif op == OP.CALL then
      local fnIdx = rd16(); local argc = rd8()
      local callee = fns[fnIdx]
      local locals = {}
      for i = 0, callee.nlocals - 1 do locals[i] = NULL end
      for k = argc - 1, 0, -1 do locals[k] = pop() end
      frame.ip = ip
      fp = fp + 1; frames[fp] = frame
      frame = { code = callee.code, ip = 0, locals = locals }
      code = frame.code; ip = 0
    elseif op == OP.RET then
      local rv = pop()
      if fp == 0 then return rv end
      frame = frames[fp]; frames[fp] = nil; fp = fp - 1
      code = frame.code; ip = frame.ip
      push(rv)
    elseif op == OP.CALL_HOST then
      local nameIdx = rd16(); local hargc = rd8()
      local hargs = {}
      for j = hargc - 1, 0, -1 do hargs[j] = pop() end
      push(host(consts[nameIdx], hargs))
    elseif op == OP.NEW_ARR then
      local n = rd16(); local arr = newArr(n)
      for m = n - 1, 0, -1 do arr[m] = pop() end
      push(arr)
    elseif op == OP.ARR_GET then local idx = pop(); local arr = pop(); push(arr[idx])
    elseif op == OP.ARR_SET then local val = pop(); local idx = pop(); local arr = pop(); arr[idx] = val; if idx + 1 > arr.n then arr.n = idx + 1 end; push(val)
    elseif op == OP.PRINT then print(toStr(pop()))
    else error('illegal opcode ' .. tostring(op)) end
  end
end

local ok, err = pcall(function() run(load()) end)
if not ok then
  io.stderr:write('[vm-gen] ' .. tostring(err) .. '\\n')
  os.exit(1)
end
`;
}

module.exports = { emitLua };
