'use strict';
// Emit a standalone JavaScript VM that embeds and executes a protected image.
// The generated file has NO dependency on this project -- it decrypts and runs
// the bytecode entirely on its own.

const { OP_NAME } = require('./opcodes');

function opConstBlock() {
  return OP_NAME.map((n, i) => `  ${n}: ${i}`).join(',\n');
}

function emitJs(image, opts = {}) {
  const b64 = Buffer.from(image).toString('base64');
  const banner = opts.banner !== false;

  return `${banner ? `// Generated by vm-gen -- standalone protected JavaScript VM.
// Do not edit: the embedded image is integrity-checked at startup.
` : ''}'use strict';
(function () {
  var IMAGE_B64 = ${JSON.stringify(b64)};

  var OP = {
${opConstBlock()}
  };

  var MASK32 = 0x100000000;
  function mul32(a, b) {
    a = a % MASK32; b = b % MASK32;
    var ah = Math.floor(a / 65536), al = a % 65536;
    var r = ((ah * b) % 65536) * 65536 + al * b;
    return r % MASK32;
  }
  function lcgNext(s) { return (mul32(s, 1664525) + 1013904223) % MASK32; }
  function ksByte(s) { return Math.floor(s / 16777216) % 256; }
  function fnSeed(codeSeed, idx) { return (codeSeed + mul32(idx, 2654435761)) % MASK32; }
  function cipher(bytes, seed) {
    var st = seed % MASK32, out = new Array(bytes.length);
    for (var i = 0; i < bytes.length; i++) { st = lcgNext(st); out[i] = (bytes[i] ^ ksByte(st)) & 0xff; }
    return out;
  }
  function fnv1a(bytes) {
    var h = 2166136261;
    for (var i = 0; i < bytes.length; i++) {
      var low = h % 256;
      h = h - low + (low ^ bytes[i]);
      h = mul32(h, 16777619);
    }
    return h % MASK32;
  }

  function decodeB64(s) {
    if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'base64'));
    var bin = atob(s), a = new Array(bin.length);
    for (var i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
    return a;
  }
  function utf8(bytes) {
    if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('utf8');
    return decodeURIComponent(escape(String.fromCharCode.apply(null, bytes)));
  }

  // ---- parse + verify the protected image ----
  function load() {
    var b = decodeB64(IMAGE_B64);
    if (b[0] !== 0x56 || b[1] !== 0x47) throw new Error('bad magic');
    if (b[2] !== 1) throw new Error('bad version');
    var checksum = b[3] + b[4] * 256 + b[5] * 65536 + b[6] * 16777216;
    var body = b.slice(7);
    if (fnv1a(body) !== (checksum % MASK32)) throw new Error('integrity check failed: image tampered');

    var p = 0;
    function u8() { return body[p++]; }
    function u16() { var v = body[p] | (body[p + 1] << 8); p += 2; return v; }
    function u32() { var v = body[p] + body[p + 1] * 256 + body[p + 2] * 65536 + body[p + 3] * 16777216; p += 4; return v; }

    var codeSeed = u32(), constSeed = u32();
    var numCanon = u8();
    var byte2canon = {};
    for (var i = 0; i < numCanon; i++) byte2canon[u8()] = i;

    var constCount = u16();
    var encConstLen = u32();
    var encConst = body.slice(p, p + encConstLen); p += encConstLen;
    var constBlob = cipher(encConst, constSeed);
    var consts = [];
    var cp = 0;
    for (var c = 0; c < constCount; c++) {
      var tag = constBlob[cp++];
      var len = constBlob[cp] | (constBlob[cp + 1] << 8); cp += 2;
      var raw = constBlob.slice(cp, cp + len); cp += len;
      var str = utf8(raw);
      consts.push(tag === 0 ? parseFloat(str) : str);
    }

    var fnCount = u16();
    var fns = [];
    for (var f = 0; f < fnCount; f++) {
      var nl = u8();
      var name = utf8(body.slice(p, p + nl)); p += nl;
      var nparams = u8();
      var nlocals = u16();
      var codeLen = u32();
      var enc = body.slice(p, p + codeLen); p += codeLen;
      fns.push({ name: name, nparams: nparams, nlocals: nlocals, code: cipher(enc, fnSeed(codeSeed, f)) });
    }
    return { byte2canon: byte2canon, consts: consts, fns: fns };
  }

  // ---- value helpers ----
  function toStr(v) {
    if (v === null || v === undefined) return 'null';
    if (v === true) return 'true';
    if (v === false) return 'false';
    if (typeof v === 'number') return Number.isInteger(v) ? String(v) : String(v);
    if (Array.isArray(v)) { var r = []; for (var i = 0; i < v.length; i++) r.push(toStr(v[i])); return '[' + r.join(', ') + ']'; }
    return String(v);
  }
  function truthy(v) { return !(v === null || v === undefined || v === false || v === 0 || v === ''); }
  function u32of(n) { return n >>> 0; }

  function host(name, args) {
    switch (name) {
      case 'len': return Array.isArray(args[0]) ? args[0].length : String(args[0]).length;
      case 'str': return toStr(args[0]);
      case 'num': return parseFloat(args[0]);
      case 'floor': return Math.floor(args[0]);
      case 'abs': return Math.abs(args[0]);
      case 'rand': return Math.random();
      case 'time': return Date.now();
      case 'push': args[0].push(args[1]); return args[0];
      default: throw new Error('unknown host builtin ' + name);
    }
  }

  function run(prog) {
    var b2c = prog.byte2canon, consts = prog.consts, fns = prog.fns;
    var stack = [];
    var frames = [];
    var frame = { fn: fns[0], ip: 0, locals: new Array(fns[0].nlocals).fill(null) };

    function rd8() { return frame.fn.code[frame.ip++]; }
    function rd16() { var lo = frame.fn.code[frame.ip], hi = frame.fn.code[frame.ip + 1]; frame.ip += 2; return lo | (hi << 8); }

    for (;;) {
      var op = b2c[rd8()];
      switch (op) {
        case OP.HALT: return;
        case OP.PUSH_CONST: stack.push(consts[rd16()]); break;
        case OP.PUSH_TRUE: stack.push(true); break;
        case OP.PUSH_FALSE: stack.push(false); break;
        case OP.PUSH_NULL: stack.push(null); break;
        case OP.POP: stack.pop(); break;
        case OP.DUP: stack.push(stack[stack.length - 1]); break;
        case OP.LOAD: stack.push(frame.locals[rd16()]); break;
        case OP.STORE: frame.locals[rd16()] = stack.pop(); break;
        case OP.ADD: { var b = stack.pop(), a = stack.pop(); stack.push((typeof a === 'number' && typeof b === 'number') ? a + b : toStr(a) + toStr(b)); break; }
        case OP.SUB: { var b = stack.pop(), a = stack.pop(); stack.push(a - b); break; }
        case OP.MUL: { var b = stack.pop(), a = stack.pop(); stack.push(a * b); break; }
        case OP.DIV: { var b = stack.pop(), a = stack.pop(); stack.push(a / b); break; }
        case OP.MOD: { var b = stack.pop(), a = stack.pop(); stack.push(a % b); break; }
        case OP.NEG: stack.push(-stack.pop()); break;
        case OP.NOT: stack.push(!truthy(stack.pop())); break;
        case OP.EQ: { var b = stack.pop(), a = stack.pop(); stack.push(a === b); break; }
        case OP.NEQ: { var b = stack.pop(), a = stack.pop(); stack.push(a !== b); break; }
        case OP.LT: { var b = stack.pop(), a = stack.pop(); stack.push(a < b); break; }
        case OP.GT: { var b = stack.pop(), a = stack.pop(); stack.push(a > b); break; }
        case OP.LTE: { var b = stack.pop(), a = stack.pop(); stack.push(a <= b); break; }
        case OP.GTE: { var b = stack.pop(), a = stack.pop(); stack.push(a >= b); break; }
        case OP.BAND: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a & b)); break; }
        case OP.BOR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a | b)); break; }
        case OP.BXOR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a ^ b)); break; }
        case OP.SHL: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a << b)); break; }
        case OP.SHR: { var b = stack.pop(), a = stack.pop(); stack.push(u32of(a >>> b)); break; }
        case OP.JMP: { frame.ip = rd16(); break; }
        case OP.JZ: { var addr = rd16(); if (!truthy(stack.pop())) frame.ip = addr; break; }
        case OP.JNZ: { var addr = rd16(); if (truthy(stack.pop())) frame.ip = addr; break; }
        case OP.CALL: {
          var fnIdx = rd16(), argc = rd8();
          var callee = fns[fnIdx];
          var locals = new Array(callee.nlocals).fill(null);
          for (var k = argc - 1; k >= 0; k--) locals[k] = stack.pop();
          frames.push(frame);
          frame = { fn: callee, ip: 0, locals: locals };
          break;
        }
        case OP.RET: {
          var rv = stack.pop();
          if (frames.length === 0) return rv;
          frame = frames.pop();
          stack.push(rv);
          break;
        }
        case OP.CALL_HOST: {
          var nameIdx = rd16(), hargc = rd8();
          var hargs = new Array(hargc);
          for (var j = hargc - 1; j >= 0; j--) hargs[j] = stack.pop();
          stack.push(host(consts[nameIdx], hargs));
          break;
        }
        case OP.NEW_ARR: {
          var n = rd16(), arr = new Array(n);
          for (var m = n - 1; m >= 0; m--) arr[m] = stack.pop();
          stack.push(arr);
          break;
        }
        case OP.ARR_GET: { var idx = stack.pop(), arr2 = stack.pop(); stack.push(arr2[idx]); break; }
        case OP.ARR_SET: { var val = stack.pop(), idx2 = stack.pop(), arr3 = stack.pop(); arr3[idx2] = val; stack.push(val); break; }
        case OP.PRINT: { var out = (typeof process !== 'undefined' && process.stdout) ? function (s) { process.stdout.write(s + '\\n'); } : console.log; out(toStr(stack.pop())); break; }
        default: throw new Error('illegal opcode ' + op + ' at ip=' + (frame.ip - 1));
      }
    }
  }

  try {
    run(load());
  } catch (e) {
    if (typeof console !== 'undefined') console.error('[vm-gen] ' + e.message);
    if (typeof process !== 'undefined' && process.exit) process.exit(1);
  }
})();
`;
}

module.exports = { emitJs };
